UPDATE `creature_ai_texts` SET `content_loc6` = 'Si sólo tuviera un poco de vino para acompañar con mi queso...' WHERE `entry` = -941;

UPDATE `db_script_string` SET `content_loc6` = 'Mmm... buscan la cabeza de Thaelis el Hambriento. Sería una buena oportunidad para ganarme algo de oro.' WHERE `entry` = 2000000220;
UPDATE `db_script_string` SET `content_loc6` = '¡Comencemos!' WHERE `entry` = 2000000451;
UPDATE `db_script_string` SET `content_loc6` = '¡Prepárate!' WHERE `entry` = 2000000450;

UPDATE `locales_gameobject` SET `name_loc6` = 'Buzón' WHERE `entry` = 191320;

UPDATE `locales_item` SET `name_loc6` = 'Glifo de Succionar vida' WHERE `entry` = 42469;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Maldición de agonía' WHERE `entry` = 42456;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de descomposición presurosa' WHERE `entry` = 50077;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de almas' WHERE `entry` = 43394;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de súcubo' WHERE `entry` = 42471;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Dolor abrasador' WHERE `entry` = 42466;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Kilrogg' WHERE `entry` = 43391;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Entereza ligada al hielo' WHERE `entry` = 43545;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Orden oscura' WHERE `entry` = 43538;
UPDATE `locales_item` SET `name_loc6` = 'Glifo del necrófago' WHERE `entry` = 43549;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Golpe sangriento' WHERE `entry` = 43826;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Armadura inquebrantable' WHERE `entry` = 43553;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Deflagración de cadáver' WHERE `entry` = 43671;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Golpe de peste' WHERE `entry` = 43548;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Levantar a muerto' WHERE `entry` = 43673;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Pestilencia' WHERE `entry` = 43672;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de enfermedad' WHERE `entry` = 45805;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de muerte oscura' WHERE `entry` = 45804;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Aura de disparo certero' WHERE `entry` = 42915;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Salva' WHERE `entry` = 42916;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de la bestia' WHERE `entry` = 42899;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Aspecto de la víbora' WHERE `entry` = 42901;
UPDATE `locales_item` SET `name_loc6` = 'Glifo del halcón' WHERE `entry` = 42909;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Trampa de Escarcha' WHERE `entry` = 42906;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de la manada' WHERE `entry` = 43355;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Multidisparo' WHERE `entry` = 42910;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Marca del cazador' WHERE `entry` = 42907;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de fuerza poseída' WHERE `entry` = 43354;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Aliviar mascota' WHERE `entry` = 43350;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Tótem Marea de maná' WHERE `entry` = 41538;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Lava' WHERE `entry` = 41524;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Maestría en Agua' WHERE `entry` = 41541;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Tótem de cólera' WHERE `entry` = 45776;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Ola de sanación inferior' WHERE `entry` = 41535;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de vida renovada' WHERE `entry` = 43385;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Escudo de agua' WHERE `entry` = 43386;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Bramido' WHERE `entry` = 40899;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Rejuvenecimiento rápido' WHERE `entry` = 50125;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Arañazo' WHERE `entry` = 40903;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Zarpa' WHERE `entry` = 48720;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de lo Salvaje' WHERE `entry` = 43335;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Bloqueo' WHERE `entry` = 43425;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Sed de sangre' WHERE `entry` = 43416;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Última carga' WHERE `entry` = 43426;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Provocar' WHERE `entry` = 43429;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de orden' WHERE `entry` = 49084;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Torbellino' WHERE `entry` = 43432;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de victoria duradera' WHERE `entry` = 43400;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Ejecutar' WHERE `entry` = 43416;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de insultos barbáricos' WHERE `entry` = 43420;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Seccionar' WHERE `entry` = 43417;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Desgarrar' WHERE `entry` = 43423;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Golpe heroico' WHERE `entry` = 43418;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Falsa arremetida' WHERE `entry` = 43398;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Ira sangrienta' WHERE `entry` = 43396;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Cargar' WHERE `entry` = 43397;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Elemental de agua' WHERE `entry` = 42754;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Eliminar maldición' WHERE `entry` = 42753;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Explosión de Fuego' WHERE `entry` = 42740;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de gema de maná' WHERE `entry` = 42750;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Agua eterna' WHERE `entry` = 50045;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Agostar' WHERE `entry` = 42747;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Resguardo contra la Escarcha' WHERE `entry` = 43360;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Armadura de hielo' WHERE `entry` = 42743;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Resguardo contra el Fuego' WHERE `entry` = 43357;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Deflagración Arcana' WHERE `entry` = 42734;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Armadura de Escarcha' WHERE `entry` = 43359;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Intelecto Arcano' WHERE `entry` = 43339;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Cólera vengativa' WHERE `entry` = 41107;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Escudo de vengador' WHERE `entry` = 41101;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Sello de rectitud' WHERE `entry` = 43868;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Sello de venganza' WHERE `entry` = 43869;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Sello de sabiduría' WHERE `entry` = 41109;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Sello de Luz' WHERE `entry` = 41110;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Sello de orden' WHERE `entry` = 41094;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Destello de luz' WHERE `entry` = 41105;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Defensa recta' WHERE `entry` = 41100;
UPDATE `locales_item` SET `name_loc6` = 'Glifo del Sabio' WHERE `entry` = 43369;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de divinidad' WHERE `entry` = 41108;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Martillo de justicia' WHERE `entry` = 41095;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Luz Sagrada' WHERE `entry` = 41106;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Captar no-muertos' WHERE `entry` = 43368;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Armonización espiritual' WHERE `entry` = 41096;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Bendición de sabiduría' WHERE `entry` = 43366;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Añublo profano' WHERE `entry` = 45803;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Trampa explosiva' WHERE `entry` = 45733;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Nutrir' WHERE `entry` = 45603;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Instintos de supervivencia' WHERE `entry` = 46372;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Regeneración iracunda' WHERE `entry` = 45794;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Vigilancia' WHERE `entry` = 45793;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Descarga de caos' WHERE `entry` = 45781;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Bomba viva' WHERE `entry` = 45737;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Escudo de rectitud' WHERE `entry` = 45744;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Tormenta divina' WHERE `entry` = 45743;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Hambre de sangre' WHERE `entry` = 45761;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de vigor' WHERE `entry` = 42971;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Golpe fantasmal' WHERE `entry` = 42965;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Esfumarse' WHERE `entry` = 43380;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Abrasamiento mental' WHERE `entry` = 45757;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Himno de esperanza' WHERE `entry` = 45758;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Control mental' WHERE `entry` = 42405;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Espíritu redentor' WHERE `entry` = 42417;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de sombra' WHERE `entry` = 42407;
UPDATE `locales_item` SET `name_loc6` = 'Glifo de Supresión de dolor' WHERE `entry` = 45760;
UPDATE `locales_item` SET `name_loc6` = 'Vitela de arma' WHERE `entry` = 39349;
UPDATE `locales_item` SET `name_loc6` = 'Vitela de arma II' WHERE `entry` = 39350;
UPDATE `locales_item` SET `name_loc6` = 'Vitela de arma III' WHERE `entry` = 43146;
UPDATE `locales_item` SET `name_loc6` = 'Vitela de armadura' WHERE `entry` = 38682;
UPDATE `locales_item` SET `name_loc6` = 'Vitela de armadura II' WHERE `entry` = 37602;
UPDATE `locales_item` SET `name_loc6` = 'Vitela de armadura III' WHERE `entry` = 43145;
