SET NAMES UTF8;

UPDATE `locales_creature` SET `name_loc6` = 'Druman Arbolsombrío', `subname_loc6` = 'Heraldo del Festival Lunar' WHERE `entry` = 22229;
UPDATE `locales_npc_text` SET `Text0_0_loc6` = 'La celebración del Festival de Invierno es un modo de recordar lo felices que vivimos durante esta estación del año tan fría. El corazón del Festival se encuentra en Orgrimmar.', `Text0_1_loc6` = 'La celebración del Festival de Invierno es un modo de recordar lo felices que vivimos durante esta estación del año tan fría. El corazón del Festival se encuentra en Orgrimmar.' WHERE `entry` = 9706;
UPDATE `locales_npc_text` SET `Text0_0_loc6` = 'Alrededor del reno encuentras un cartel con el símbolo de Pastos Bosquehumeante y con un nombre que dice: "- Metzen".$B$BMetzen te mira con cara de tristeza y con ojos llorosos. Parece como si este reno hubiese sido inmovilizado por una fuerza invisible.' WHERE `entry` = 8076;
UPDATE `locales_npc_text` SET `Text0_0_loc6` = 'Los ojos de Metzen se iluminan con un sorprendente destello que te impresiona al verlo. Choca sus astas contra tí y emite un gruñido mostrando su agradecimiento.$B$BAlrededor de ti, empieza a surgir una energía extraña. ¡Parece que algo fuese a ocurrir!' WHERE `entry` = 8077;

UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Hay una nota en el regalo que dice:$B$B"Para $N:$B$BEn agradecimiento por tus hazañas llevadas acabo en Azeroth durante todo este año, te dejo este regalo.$B$BEspero que te guste. ¡Feliz navidad!$B$B- Gran Padre Invierno."' WHERE `entry` = 8803;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Este bonito regalo tiene tu nombre.$B$B¿A qué esperas para abrirlo?' WHERE `entry` = 8768;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Hay una nota en el regalo que dice:$B$BPara $N:$B$B"Que tengas unas felices fiestas.$B$B- Gran Padre Invierno."' WHERE `entry` = 8744;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = '"Aquí tienes un fantástico regalo del Gran Padre Invierno y de tus amigos de los Pastos Bosquehumeante."' WHERE `entry` = 8769;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Un regalo que tiene pinta de haber sido agitado muchas veces.$B$BTiene una nota que dice:$B$B"Para un $r $c muy especial."' WHERE `entry` = 8767;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Un regalo que tiene pinta de haber sido agitado muchas veces.$B$BTiene una nota que dice:$B$B"Para un $r $c muy especial."' WHERE `entry` = 8788;

UPDATE `locales_quest` SET `RequestItemsText_loc6` = 'La máquina "Conservante de acebo" es una maquina que parece buena al principio con sólo verla, pero si te pones a examinarla detenidamente, te revelta que ha sido manipulada por los goblins. Aun así, tu habilidad de cocina parece que te permite entender cómo funciona.$B$BVes que hay acebo fresco en la máquina. Simplemente necesitas meter un poco de sal de roca y 5 monedas de oro para que la máquina empiece a funcionar.', `OfferRewardText_loc6` = 'La maquina hace un ruido extraño y empieza a funcionar. Ya no hay nada que pueda pararla. De repente, empieza a salir humo muy frío. ¡Mira, aparece un acebo en conserva!' WHERE `entry` = 8799;

UPDATE `locales_quest` SET `OfferRewardText_loc6` = '<Myralion toma la empuñadura y la observa con detenimiento.>$B$B¿Esto viene de la ciudadela? ¿Qué hacía ahí? Está claro que esta hoja no la ha creado la Plaga.$B$BLas armas de tal calidad solo las pueden crear unas pocas de las criaturas de Azeroth. Tendremos que preguntarles si pueden ayudarnos a identificarla.', `RequestItemsText_loc6` = '¿Qué has descubierto?' WHERE `entry` = 24554;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = '<Caladis toma la empuñadura y la observa con detenimiento.>$B$B¿Esto viene de la ciudadela? ¿Qué hacía ahí? Está claro que esta hoja no la ha creado la Plaga.$B$BLas armas de tal calidad solo las pueden crear unas pocas de las criaturas de Azeroth. Tendremos que preguntarles si pueden ayudarnos a identificarla.', `RequestItemsText_loc6` = '¿Qué has descubierto?' WHERE `entry` = 14443;

UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Debemos recuperar el libro de El Pacto de Plata. Sin ese libro de Krasus no tenemos muchas posibilidades de resolver el misterio de la espada de la Corona de Hielo o de activar su poder.', `RequestItemsText_loc6` = '¿Qué información me traes?' WHERE `entry` = 24555;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'No podemos dejar que el libro caiga en manos de los Atracasol. Para que podamos identificar la espada y descubrir su poder, tendremos que encontrar una manera de recuperar el libro de Krasus.' WHERE `entry` = 14444;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = '<El magister Hathorel lee las órdenes que has recuperado.>$B$BEl agente que has interceptado supuestamente iba a llevar el Escrito del Reposo del Dragón a Corona de Hielo, tras reunirse con un tal arcanista Tybalin en el Enclave de Plata. Tenemos que conseguir ese libro, $N, y solo tendremos una oportunidad antes de que abandone la ciudad. Debemos actuar con rapidez.', `RequestItemsText_loc6` = '¿Tenía el agente algo que podamos aprovechar?' WHERE `entry` = 24557;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = '<El arcanista Tybalin lee las órdenes que has recuperado.>$B$BEl agente que has interceptado supuestamente iba a llevar el Escrito del Reposo del Dragón a Corona de Hielo, tras reunirse con un tal magister Hathorel en el Santuario Atracasol. Tenemos que conseguir ese libro, $N, y solo tendremos una oportunidad antes de que abandone la ciudad. Debemos actuar con rapidez.', `RequestItemsText_loc6` = '¿Tenía el agente algo que podamos aprovechar?' WHERE `entry` = 14457;

UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Sabía que Shandy encontraría una forma de ayudarnos. Deja que encante el tabardo y lo prepare para el uso. Con un poco de suerte, el dueño del tabardo nunca sabrá que nos lo llevamos y Shandy se ocupará del resto.', `RequestItemsText_loc6` = '¿Shandy te ha podido ayudar a conseguir un tabardo de los Atracasol?' WHERE `entry` = 20438;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Sabía que Shandy encontraría una forma de ayudarnos. Deja que encante el tabardo y lo prepare para el uso. Con un poco de suerte, el dueño del tabardo nunca sabrá que nos lo llevamos y Shandy se ocupará del resto.', `RequestItemsText_loc6` = '¿Shandy te ha podido ayudar a conseguir un tabardo de El Pacto de Plata?' WHERE `entry` = 24556;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Un trabajo excelente. Ahora que el escrito está en nuestras manos, tenemos que llevárselo a Myralion Resplandor lo antes posible. No podemos arriesgarnos a que el Pacto de Plata nos arrebate el libro una vez más.$B$BLe devolveré el tabardo a Shandy y me aseguraré de que se le recompense por su ayuda. Una vez que el libro esté en manos de Myralion, el Pacto de Plata dejará de ser una amenaza.', `RequestItemsText_loc6` = '¿Has recuperado el libro de Reposo del Dragón?' WHERE `entry` = 24451;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Un trabajo excelente. Ahora que el escrito está en nuestras manos, tenemos que llevárselo a Caladis Lanza Reluciente lo antes posible. No podemos arriesgarnos a que los Atracasol nos arrebaten el libro una vez más.$B$BLe devolveré el tabardo a Shandy y me aseguraré de que se le recompense por su ayuda. Una vez que el libro esté en manos de Caladis, los Atracasol dejarán de ser una amenaza.', `RequestItemsText_loc6` = '¿Has recuperado el libro de Reposo del Dragón?' WHERE `entry` = 20439;

UPDATE `locales_quest` SET `OfferRewardText_loc6` = '<Myralion recibe el pesado libro y empieza a ojearlo.>$B$BLos símbolos de la hoja me eran conocidos, y ahora sé por qué. Sin duda se trata de una espada forjada por los dragones, entregada a una de las razas mortales, ¿pero qué espada es esta y cómo llegó a Corona de Hielo?', `RequestItemsText_loc6` = 'Esperábamos tu regreso. ¿Qué te ha demorado?' WHERE `entry` = 24558;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = '<Caladis recibe el pesado libro y empieza a ojearlo.>$B$BLos símbolos de la hoja me eran conocidos, y ahora sé por qué. Sin duda se trata de una espada forjada por los dragones, entregada a una de las razas mortales, ¿pero qué espada es esta y cómo llegó a Corona de Hielo?', `RequestItemsText_loc6` = 'Esperábamos tu regreso. ¿Qué te ha demorado?' WHERE `entry` = 24454;

UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Has restaurado la hoja de Quel\'Delar, ¡desafiando abiertamente las palabras de la Reina de Sangre Lana\'thel! Aún hay que templar la hoja, antes de demostrarle a la reina la insensatez de sus palabras.', `RequestItemsText_loc6` = '¿Has podido reconstruir Quel\'Delar?' WHERE `entry` = 24559;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Has restaurado la hoja de Quel\'Delar, ¡desafiando abiertamente las palabras de la Reina de Sangre Lana\'thel! Aún hay que templar la hoja, antes de demostrarle a la reina la insensatez de sus palabras.', `RequestItemsText_loc6` = '¿Has podido reconstruir Quel\'Delar?' WHERE `entry` = 24461;

UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Al templarla, la espada debería haber quedado restaurada. ¿Por qué no ha funcionado?', `RequestItemsText_loc6` = 'La espada será inútil hasta que la hayas templado.' WHERE `entry` = 24560;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Al templarla, la espada debería haber quedado restaurada. ¿Por qué no ha funcionado?', `RequestItemsText_loc6` = 'La espada será inútil hasta que la hayas templado.' WHERE `entry` = 24476;

UPDATE `locales_quest` SET `OfferRewardText_loc6` = '¿Cómo puede asentarse el mal en una espada como esta? Me habría parecido imposible si no lo estuviera viendo con mis propios ojos. Si fue posible corromper la mayor creación de los dragones y usarla contra ellos, ¿por qué no una mera espada?$B$BCreo que Uther tiene razón. Debes apresurarte en hacer lo que te dice, $N.', `RequestItemsText_loc6` = '¿Qué ha sucedido en las Cámaras de Reflexión?' WHERE `entry` = 24561;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = '¿Cómo puede asentarse el mal en una espada como esta? Me habría parecido imposible si no lo estuviera viendo con mis propios ojos. Si fue posible corromper la mayor creación de los dragones y usarla contra ellos, ¿por qué no una mera espada?$B$BCreo que Uther tiene razón. Debes apresurarte en hacer lo que te dice, $N.', `RequestItemsText_loc6` = '¿Qué ha sucedido en las Cámaras de Reflexión?' WHERE `entry` = 24480;

UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Espero que comprendas que no te puedo dejar pasar a la Fuente del Sol sin más, $N. Es el lugar más sagrado de los sin\'dorei y acabamos de recuperarlo.$B$B¿Piensas darnos esperanzas con historias de Quel\'Delar? Si no tienes pruebas de lo que dices, no veo razón para creer en tus palabras.', `RequestItemsText_loc6` = '¿Qué te trae por aquí?' WHERE `entry` = 24562;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Espero que comprendas que no te puedo dejar pasar a la Fuente del Sol sin más, $N. Es el lugar más sagrado de los sin\'dorei y acabamos de recuperarlo.$B$B¿Piensas darnos esperanzas con historias de Quel\'Delar? Si no tienes pruebas de lo que dices, no veo razón para creer en tus palabras.', `RequestItemsText_loc6` = '¿Qué te trae por aquí?' WHERE `entry` = 24522;

UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Es verdad que eres portador de Quel\'Delar. Este es un gran día para toda Quel\'Thalas y los sin\'dorei. Tienes mi permiso para entrar en la Fuente del Sol y completar la restauración de la espada. Mantén la cabeza alta, $N. Los hijos de Lunargenta han soñado con este día durante años.', `RequestItemsText_loc6` = '¿Has visitado el lugar en el que Thalorien cayó defendiendo la Fuente del Sol?' WHERE `entry` = 24563;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Es verdad que eres portador de Quel\'Delar. Este es un gran día para toda Quel\'Thalas y los sin\'dorei. Tienes mi permiso para entrar en la Fuente del Sol y completar la restauración de la espada. Mantén la cabeza alta, $N. Los hijos de Lunargenta han soñado con este día durante años.', `RequestItemsText_loc6` = '¿Has visitado el lugar en el que Thalorien cayó defendiendo la Fuente del Sol?' WHERE `entry` = 24535;

UPDATE `locales_quest` SET `OfferRewardText_loc6` = '¿Es el arma de Thalorien Buscalba lo que ven mis ojos? ¡Es un día glorioso para los Atracasol y para todos los sin\'dorei!', `RequestItemsText_loc6` = '¿Qué ha ocurrido dentro de la Fuente del Sol?' WHERE `entry` = 24596;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = '¿Es el arma de Thalorien Buscalba lo que ven mis ojos? ¡Es un día glorioso para los Atracasol y para todos los sin\'dorei!', `RequestItemsText_loc6` = '¿Qué ha ocurrido dentro de la Fuente del Sol?' WHERE `entry` = 24598;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = '¿Es el arma de Thalorien Buscalba lo que ven mis ojos? ¡Es un día glorioso para los Atracasol y para todos los sin\'dorei!', `RequestItemsText_loc6` = '¿Qué ha ocurrido dentro de la Fuente del Sol?' WHERE `entry` = 24594;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = '¿Es el arma de Thalorien Buscalba lo que ven mis ojos? ¡Es un día glorioso para los Atracasol y para todos los sin\'dorei!', `RequestItemsText_loc6` = '¿Qué ha ocurrido dentro de la Fuente del Sol?' WHERE `entry` = 24564;

UPDATE `locales_quest` SET `OfferRewardText_loc6` = '¿Es el arma de Thalorien Buscalba lo que ven mis ojos? ¡No puedo creerlo! ¡Lo has conseguido, $N!', `RequestItemsText_loc6` = '¿Qué ha ocurrido dentro de la Fuente del Sol?' WHERE `entry` = 24595;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = '¿Es el arma de Thalorien Buscalba lo que ven mis ojos? ¡No puedo creerlo! ¡Lo has conseguido, $N!', `RequestItemsText_loc6` = '¿Qué ha ocurrido dentro de la Fuente del Sol?' WHERE `entry` = 24553;

UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Quel\'Delar se alza de nuevo, como nos alzamos los sin\'dorei de las cenizas de la derrota y la traición. Y, sin embargo, el arma de Thalorien Buscalba ha decidido servir a un extraño.$B$BTranquilo, $N. No pretendo quitarle hierro a tu hazaña, ya que has conseguido lo que no pudo ninguno de mis hermanos, aunque no sepa por qué. Salta a la vista que te corresponde a ti portar la espada: ya se está adaptando a tus habilidades. Blande a Quel\'Delar con orgullo contra nuestros enemigos comunes.', `RequestItemsText_loc6` = '¿Es cierto que has restaurado Quel\'Delar?' WHERE `entry` = 24801;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Quel\'Delar se alza de nuevo, como nos alzamos los sin\'dorei de las cenizas de la derrota y la traición. Y, sin embargo, el arma de Thalorien Buscalba ha decidido servir a un extraño.$B$BTranquilo, $N. No pretendo quitarle hierro a tu hazaña, ya que has conseguido lo que no pudo ninguno de mis hermanos, aunque no sepa por qué. Salta a la vista que te corresponde a ti portar la espada: ya se está adaptando a tus habilidades. Blande a Quel\'Delar con orgullo contra nuestros enemigos comunes.', `RequestItemsText_loc6` = '¿Es cierto que has restaurado Quel\'Delar?' WHERE `entry` = 24800;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Esa es la espada de inmenso poder que has redimido del poder demoníaco que la había absorbido, y en un gran día como hoy, $N. Con Quel\'Delar y la fuerza de los Atracasol y sus aliados, el Rey Exánime no tendrá nada que hacer contra nosotros.$B$BHoy, toda la Horda te reconoce como $gun:una $ghéroe:heroína.$B$BLa Cruzada Argenta tiene un magnífico arsenal para nuestros aliados más fuertes. Permíteme que te ofrezca una de nuestras mejores armas con la misma calidad que Quel\'Delar.', `RequestItemsText_loc6` = '¿Es cierto que has restaurado Quel\'Delar?' WHERE `entry` = 24799;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Esa es la espada de inmenso poder que has redimido del poder demoníaco que la había absorbido, y en un gran día como hoy, $N. Con Quel\'Delar y la fuerza de los Atracasol y sus aliados, el Rey Exánime no tendrá nada que hacer contra nosotros.$B$BHoy, los sin\'dorei y toda Lunargenta te reconoce como $gun:una $ghéroe:heroína.$B$BLa Cruzada Argenta tiene un magnífico arsenal para nuestros aliados más fuertes. Permíteme que te ofrezca una de nuestras mejores armas con la misma calidad que Quel\'Delar.', `RequestItemsText_loc6` = '¿Es cierto que has restaurado Quel\'Delar?' WHERE `entry` = 24798;

UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Quel\'Delar se alza de nuevo, como nos alzamos los sin\'dorei de las cenizas de la derrota y la traición. Y, sin embargo, el arma de Thalorien Buscalba ha decidido servir a un extraño.$B$BTranquilo, $N. No pretendo quitarle hierro a tu hazaña, ya que has conseguido lo que no pudo ninguno de mis hermanos, aunque no sepa por qué. Salta a la vista que te corresponde a ti portar la espada: ya se está adaptando a tus habilidades. Blande a Quel\'Delar con orgullo contra nuestros enemigos comunes.', `RequestItemsText_loc6` = '¿Es cierto que has restaurado Quel\'Delar?' WHERE `entry` = 24795;
UPDATE `locales_quest` SET `OfferRewardText_loc6` = 'Esa es la espada de inmenso poder que has redimido del poder demoníaco que la había absorbido, y en un gran día como hoy, $N. Con Quel\'Delar y la fuerza de El Pacto de Plata y sus aliados, el Rey Exánime no tendrá nada que hacer contra nosotros.$B$BHoy, toda la Alianza te reconoce como $gun:una $ghéroe:heroína.$B$BLa Cruzada Argenta tiene un magnífico arsenal para nuestros aliados más fuertes. Permíteme que te ofrezca una de nuestras mejores armas con la misma calidad que Quel\'Delar.', `RequestItemsText_loc6` = '¿Es cierto que has restaurado Quel\'Delar?' WHERE `entry` = 24796;

-- UPDATE `locales_quest` SET `OfferRewardText_loc6` = '', `RequestItemsText_loc6` = '' WHERE `entry` = 8803;

UPDATE `locales_quest` SET `Title_loc6` = 'Destino y coincidencia', `Details_loc6` = 'En este mundo, hay dos tipos de personas, $N: los que creen en las coincidencias y los que no.$B$BEl día que perdí la vista recibí el don de la clarividencia. Supongo que te preguntarás a qué tipo de personas pertenezco yo.$B$BHoy vino una joven llamada Sasha que tuvo la misma visión que tú. Ve a hablar con ella.$B$BLa encontrarás al este de aquí en el Puesto de Venta de Pino Blanco de camino hacia el Poblado Solsticio.', `Objectives_loc6` = 'Habla con Sasha en el Puesto de Venta de Pino Blanco.' WHERE `entry` = 12329;

UPDATE `locales_gossip_menu_option` SET `option_text_loc6` = 'Rasganorte requiere tu atención, Señor supremo Grito Infernal. Nos encargaremos del Rey Exánime y sus esbirros sin tu ayuda.' WHERE `menu_id` = '11206' AND `id` = '0';
UPDATE `locales_gossip_menu_option` SET `option_text_loc6` = 'Está decidido. ¡El Rey Exánime morirá por nuestra mano!' WHERE `menu_id` = '11207' AND `id` = '0';

UPDATE `locales_npc_text` SET `Text0_0_loc6` = '¿Declináis el poder de la Ofensiva Grito de Guerra? ¿Acaso el caos de la batalla os ha arrebatado la cordura? ¡Con mi ayuda, la victoria está a nuestro alcance! Sin ella, la lucha será difícil.' WHERE `entry` = 15608;
UPDATE `locales_npc_text` SET `Text0_0_loc6` = '¡Gloria a la Horda!' WHERE `entry` = 15609;
UPDATE `locales_npc_text` SET `Text0_0_loc6` = 'El Pacto de Plata hará lo que sea con tal de fastidiar los planes de los Atracasol. Debemos mantenernos alerta en todo momento.' WHERE `entry` = 15074;
UPDATE `locales_npc_text` SET `Text0_0_loc6` = 'Parece que estos son los restos de Thalorien Buscalba, el último portador de Quel\'Delar.' WHERE `entry` = 15155;
UPDATE `locales_npc_text` SET `Text0_0_loc6` = 'Te escoltaré hasta que llegemos a la Fuente del Sol. Avísame cuando estés listo.' WHERE `entry` = 15240;

UPDATE `locales_gossip_menu_option` SET `option_text_loc6` = 'Quiero ver mi banco.' WHERE `menu_id` = 33239 AND `id` = 0;
UPDATE `locales_gossip_menu_option` SET `option_text_loc6` = 'Quiero ver tus mercancías.' WHERE `menu_id` = 33239 AND `id` = 1;
UPDATE `locales_gossip_menu_option` SET `option_text_loc6` = 'Quiero ver mi buzón.' WHERE `menu_id` = 33239 AND `id` = 2;
UPDATE `locales_gossip_menu_option` SET `option_text_loc6` = 'Grímpola de Orgrimmar' WHERE `menu_id` = 33239 AND `id` = 3;
UPDATE `locales_gossip_menu_option` SET `option_text_loc6` = 'Grímpola de Sen\'jin' WHERE `menu_id` = 33239 AND `id` = 4;
UPDATE `locales_gossip_menu_option` SET `option_text_loc6` = 'Grímpola de Lunargenta' WHERE `menu_id` = 33239 AND `id` = 5;
UPDATE `locales_gossip_menu_option` SET `option_text_loc6` = 'Grímpola de Cima del Trueno' WHERE `menu_id` = 33239 AND `id` = 6;
UPDATE `locales_gossip_menu_option` SET `option_text_loc6` = 'Grímpola de Entrañas' WHERE `menu_id` = 33239 AND `id` = 7;
UPDATE `locales_gossip_menu_option` SET `option_text_loc6` = 'Yo me encargo de liberarlo.' WHERE `menu_id` = 9184 AND `id` = 0;
UPDATE `locales_gossip_menu_option` SET `option_text_loc6` = '¿Qué sabes acerca de antiguas espadas?' WHERE `menu_id` = 10199 AND `id` = 1;
UPDATE `locales_gossip_menu_option` SET `option_text_loc6` = '¿Qué sabes acerca de antiguas espadas?' WHERE `menu_id` = 10199 AND `id` = 2;
UPDATE `locales_gossip_menu_option` SET `option_text_loc6` = 'Magister Hathorel me ha dicho que quizá podrías prestarme cierto tabardo.' WHERE `menu_id` = 10854 AND `id` = 0;
UPDATE `locales_gossip_menu_option` SET `option_text_loc6` = 'Arcanista Tybalin me ha dicho que quizá podrías prestarme cierto tabardo.' WHERE `menu_id` = 10854 AND `id` = 1;
UPDATE `locales_gossip_menu_option` SET `option_text_loc6` = 'Entregaré el tomo a nuestros contactos en Corona de Hielo, magister.' WHERE `menu_id` = 10857 AND `id` = 1;
UPDATE `locales_gossip_menu_option` SET `option_text_loc6` = 'Entregaré el tomo a nuestros contactos en Corona de Hielo, arcanista.' WHERE `menu_id` = 10858 AND `id` = 1;

UPDATE `db_script_string` SET `content_loc6` = 'Troools... de la plaaagaaa... ardiendooo...' WHERE `entry` = 2000001031;
UPDATE `db_script_string` SET `content_loc6` = '... en un fuego abiertooo...' WHERE `entry` = 2000001032;
UPDATE `db_script_string` SET `content_loc6` = 'Mack Miedosen hace un rápido parpadeo de ojos.' WHERE `entry` = 2000001033;
UPDATE `db_script_string` SET `content_loc6` = 'Espera un momento... ¿pero qué...?... ¿en qué estaría pensando?' WHERE `entry` = 2000001034;
UPDATE `db_script_string` SET `content_loc6` = 'Muchas gracias, $r. Me llevaré a este miserable ahora mismo. ¡Andando!' WHERE `entry` = 2000000477;
UPDATE `db_script_string` SET `content_loc6` = 'Llegas tarde, $N. Otro visitante de Dalaran vino pidiendo información sobre las mismas hojas prismáticas de los dragones.' WHERE `entry` = 2000000084;
UPDATE `db_script_string` SET `content_loc6` = 'Por tu descripción, estoy seguro de que el libro que le presté al visitante podría permitirte identificar con facilidad el arma.' WHERE `entry` = 2000000085;
UPDATE `db_script_string` SET `content_loc6` = 'Me temo que le tendrás que preguntar a... Quizá Kalecgos pueda ayudar.' WHERE `entry` = 2000000086;
UPDATE `db_script_string` SET `content_loc6` = 'Puede que $N haya encontrado los restos de una espada prismática. ¿Ofrecerías tu ayuda a nuestro visitante?' WHERE `entry` = 2000000095;
UPDATE `db_script_string` SET `content_loc6` = '¿Estás seguro de que deberías estar ayudando a estos mortales en su misión en busca de la espada?' WHERE `entry` = 2000000100;
UPDATE `db_script_string` SET `content_loc6` = 'Estas espadas, Krasus... se forjaron hace mucho tiempo, cuando las cosas eran... diferentes.' WHERE `entry` = 2000000101;
UPDATE `db_script_string` SET `content_loc6` = '¿Crees que nuestros aliados no podrán controlar el poder de las espadas?' WHERE `entry` = 2000000096;
UPDATE `db_script_string` SET `content_loc6` = 'Una vez, nuestros enemigos utilizaron nuestra mejor arma en nuestra contra. ¿Qué te hace pensar que será distinto con las espadas prismáticas?' WHERE `entry` = 2000000105;
UPDATE `db_script_string` SET `content_loc6` = 'Durante mucho tiempo los campeones mortales han utilizado estas armas para combatir el mal. No veo por qué las espadas no habrían de participar en esta batalla.' WHERE `entry` = 2000000097;
UPDATE `db_script_string` SET `content_loc6` = 'Como desees, mi reina. No me interpondré en su camino pero los vigilaré de cerca.' WHERE `entry` = 2000000106;
UPDATE `db_script_string` SET `content_loc6` = 'Como todos.' WHERE `entry` = 2000000093;
UPDATE `db_script_string` SET `content_loc6` = 'Por favor, mortal, busca al magister Hathorel en Dalaran. Puede que el pueda negociar con El Pacto de Plata para acceder el libro.' WHERE `entry` = 2000000063;
UPDATE `db_script_string` SET `content_loc6` = 'Por favor, mortal, busca al arcanista Tybalin en Dalaran. Puede que el pueda negociar con los Atracasol para acceder el libro.' WHERE `entry` = 2000000057;
UPDATE `db_script_string` SET `content_loc6` = 'Me alegro de verte al fin, mensajero. Krasus nos ha confiado una de las pocas copias que quedan de Hojas antiguas forjadas por los dragones.' WHERE `entry` = 2000000492;
UPDATE `db_script_string` SET `content_loc6` = 'Aquí está tu libro. Asegúrate de que llegue a Caladis Lanza Reluciente en Corona de Hielo antes de que los Atracasol se den cuenta de lo que está ocurriendo.' WHERE `entry` = 2000000435;
UPDATE `db_script_string` SET `content_loc6` = '¡Viaja rápido! Los Atracasol no desperdiciarán ni un minuto en cuanto sepan que tenemos la información que buscan.' WHERE `entry` = 2000000436;
UPDATE `db_script_string` SET `content_loc6` = 'Llegas tarde, mensajero. No, no quiero oír excusas; un sólo error puede ser fatal para nuestros planes.' WHERE `entry` = 2000000432;
UPDATE `db_script_string` SET `content_loc6` = 'Aquí tienes el libro de Reposo del Dragón. Debes llevárselo inmediatamente Myralion Resplandor.' WHERE `entry` = 2000000433;
UPDATE `db_script_string` SET `content_loc6` = 'Esperaré tu regreso, mensajero. No me hace falta recordarte el valor que tiene este libro, el hecho de que este libro caiga en las manos de El Pacto de Plata puede echar abajo nuestros planes, y no debe haber nada que nos detenga.' WHERE `entry` = 2000000434;

UPDATE `creature_ai_texts` SET `content_loc6` = 'Llegas tarde, sobrestante.' WHERE `entry` = -272121;
UPDATE `creature_ai_texts` SET `content_loc6` = 'El destino no espera. Tienes que seguir haciendo muchos más gólems de guerra, o el líder gigante de piedra y sus esbirros se harán con el poder de Ulduar.' WHERE `entry` = -272122;
UPDATE `creature_ai_texts` SET `content_loc6` = 'Sigue insistiéndoles. En caso de que se niegen, enviámelos para destruirlos.' WHERE `entry` = -272123;
UPDATE `creature_ai_texts` SET `content_loc6` = 'Si los gigantes de piedra interfieren con mi trabajo en Ulduar, te haré a ti y a tu escuadrón responsables de ello. Los mortales no pueden permitirse hacerle cara a la fuerza de los gigantes.' WHERE `entry` = -272124;
UPDATE `creature_ai_texts` SET `content_loc6` = 'Regresa a tu puesto de trabajo, sobrestante. Asegúrate de que tus hombres trabajen como es debido.' WHERE `entry` = -272125;
UPDATE `creature_ai_texts` SET `content_loc6` = '¿Preparado para jugar?' WHERE `entry` = -801;
UPDATE `creature_ai_texts` SET `content_loc6` = 'Sé para qué has venido. Uno de tus superiores te ha mandado para que te informe sobre sobre los magnatauros. ¿Qué crees que puedes hacer para que hable, perro?' WHERE `entry` = -892;
UPDATE `creature_ai_texts` SET `content_loc6` = '¡Está bien! ¡Para, hablaré! El magnatauro que buscáis se llama Grom\'thar, el Portador del Trueno. Ya puedes tener cuidado con él, o de lo contrario experimentarás la mayor dolorosa de las muertes.' WHERE `entry` = -893;
UPDATE `creature_ai_texts` SET `content_loc6` = '¿Quién eres?' WHERE `entry` = -498;
UPDATE `creature_ai_texts` SET `content_loc6` = 'Me parece una osadía que retes al poder de los elementos. Te haré pagar por ello.' WHERE `entry` = -500;
UPDATE `creature_ai_texts` SET `content_loc6` = 'Me aburro. ¡Acabaré contigo!' WHERE `entry` = -501;
UPDATE `creature_ai_texts` SET `content_loc6` = '¡PARA!' WHERE `entry` = -499;

UPDATE `creature_ai_texts` SET `content_loc7` = `content_loc6`;
UPDATE `db_script_string` SET `content_loc7` = `content_loc6`;
UPDATE `mangos_string` SET `content_loc7` = `content_loc6`;
UPDATE `locales_achievement_reward` SET `subject_loc7` = `subject_loc6`, `text_loc7` = `text_loc6`;
UPDATE `locales_creature` SET `name_loc7` = `name_loc6`, `subname_loc7` = `subname_loc6`;
UPDATE `locales_gameobject` SET `name_loc7` = `name_loc6`, `castbarcaption_loc7` = `castbarcaption_loc6`;
UPDATE `locales_gossip_menu_option` SET `option_text_loc7` = `option_text_loc6`;
UPDATE `locales_item` SET `name_loc7` = `name_loc6`, `description_loc7` = `description_loc6`;
UPDATE `locales_npc_text` SET `Text0_0_loc7` = `Text0_0_loc6`, `Text0_1_loc7` = `Text0_1_loc6`, `Text1_0_loc7` = `Text1_0_loc6`, `Text1_1_loc7` = `Text1_1_loc6`;
UPDATE `locales_page_text` SET `Text_loc7` = `Text_loc6`;
UPDATE `locales_quest` SET `Title_loc7` = `Title_loc6`, `Details_loc7` = `Details_loc6`, `Objectives_loc7` = `Objectives_loc6`, `OfferRewardText_loc7` = `OfferRewardText_loc6`, `RequestItemsText_loc7` = `RequestItemsText_loc6`, `EndText_loc7` = `EndText_loc6`, `CompletedText_loc7` = `CompletedText_loc6`, `ObjectiveText1_loc7` = `ObjectiveText1_loc6`, `ObjectiveText2_loc7` = `ObjectiveText2_loc6`, `ObjectiveText3_loc7` = `ObjectiveText3_loc6`, `ObjectiveText4_loc7` = `ObjectiveText4_loc6`;