-- ============================== --
--    ACID [creature_ai_texts]    --
-- ============================== --


ALTER TABLE `creature_ai_texts` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;



UPDATE `creature_ai_texts` SET `content_loc7`='Parece que esos idiotas de la Abadia nos han enviado carne fresca.' WHERE `entry`='-1';
UPDATE `creature_ai_texts` SET `content_loc7`='La Hermandad no tolerara tus actos.' WHERE `entry`='-2';
UPDATE `creature_ai_texts` SET `content_loc7`='Ah, una oportunidad para usar esta hoja recien afilada.' WHERE `entry`='-3';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Siente el poder de la Hermandad!' WHERE `entry`='-4';
UPDATE `creature_ai_texts` SET `content_loc7`='Mas huesos para roer...' WHERE `entry`='-5';
UPDATE `creature_ai_texts` SET `content_loc7`='Grrrr... ¡carne fresca!' WHERE `entry`='-6';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Tu no llevarte vela!' WHERE `entry`='-7';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Yujuuuuuu! ¡Yo correr!.' WHERE `entry`='-8';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Que significa esta impertinencia? ¡Morireis!' WHERE `entry`='-9';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Gritad mientras ardeis!' WHERE `entry`='-10';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Os incinerare!' WHERE `entry`='-11';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Me regocijo con tu dolor!' WHERE `entry`='-12';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Quieres un premio, eh? ¿Que tal la muerte?' WHERE `entry`='-13';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Tu vida sera mia!' WHERE `entry`='-14';
UPDATE `creature_ai_texts` SET `content_loc7`='Odio recordarte que te avise...' WHERE `entry`='-15';
UPDATE `creature_ai_texts` SET `content_loc7`='No ireis... muy lejos.' WHERE `entry`='-16';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Que haceis? ¡Estos especimenes son muy delicados!' WHERE `entry`='-17';
UPDATE `creature_ai_texts` SET `content_loc7`='¡La naturaleza se somete a mi voluntad!' WHERE `entry`='-18';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Endorel aluminor!' WHERE `entry`='-19';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Ha concluido tu ciclo vital!' WHERE `entry`='-20';
UPDATE `creature_ai_texts` SET `content_loc7`='Hay que conservar... los especimenes...' WHERE `entry`='-21';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Van Cleef paga mucho por vuestras cabezas!' WHERE `entry`='-22';
UPDATE `creature_ai_texts` SET `content_loc7`='¡En guardia!' WHERE `entry`='-23';
UPDATE `creature_ai_texts` SET `content_loc7`='Defendeos, aunque no os servira de mucho...' WHERE `entry`='-24';
UPDATE `creature_ai_texts` SET `content_loc7`='Lo sabia, sabia que... era la unica salida.' WHERE `entry`='-25';
UPDATE `creature_ai_texts` SET `content_loc7`='Si, muy satisfactorio.' WHERE `entry`='-26';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Al fin, un objetivo para mis frustraciones!' WHERE `entry`='-27';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Habeis venido para matar a Dalliah? ¿Puedo mirar?' WHERE `entry`='-28';
UPDATE `creature_ai_texts` SET `content_loc7`='La oscuridad... lo consume todo.' WHERE `entry`='-29';
UPDATE `creature_ai_texts` SET `content_loc7`='Las sombras... os engulliran.' WHERE `entry`='-30';
UPDATE `creature_ai_texts` SET `content_loc7`='Este... ya esta vacio.' WHERE `entry`='-31';
UPDATE `creature_ai_texts` SET `content_loc7`='No... mas... vida.' WHERE `entry`='-32';
UPDATE `creature_ai_texts` SET `content_loc7`='El vacio... se avecina.' WHERE `entry`='-33';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Dar un paso adelante! Os dare la bienvenida que os mereceis.' WHERE `entry`='-34';
UPDATE `creature_ai_texts` SET `content_loc7`='Oh, deja de lloriquear.' WHERE `entry`='-35';
UPDATE `creature_ai_texts` SET `content_loc7`='Aun no... he empezado...' WHERE `entry`='-36';
UPDATE `creature_ai_texts` SET `content_loc7`='Ya no os enfrentais a un subordinado.' WHERE `entry`='-37';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Band\'or shorel\'aran!' WHERE `entry`='-38';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Guardias! ¡Reducir a los invasores!' WHERE `entry`='-39';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Es este el final?' WHERE `entry`='-40';
UPDATE `creature_ai_texts` SET `content_loc7`='Que llegara a ser de...' WHERE `entry`='-41';
UPDATE `creature_ai_texts` SET `content_loc7`='Ha llegado la hora de que te unas a nosotros, $C.' WHERE `entry`='-42';
UPDATE `creature_ai_texts` SET `content_loc7`='¡No!' WHERE `entry`='-43';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Estoy acabado!' WHERE `entry`='-44';
UPDATE `creature_ai_texts` SET `content_loc7`='El maestro... se enfadara...' WHERE `entry`='-45';
UPDATE `creature_ai_texts` SET `content_loc7`='¡%s se enfurecio!' WHERE `entry`='-46';
UPDATE `creature_ai_texts` SET `content_loc7`='¡%s intenta huir despavorido!' WHERE `entry`='-47';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Habeis sido descubierto por el ojo de Grillok!' WHERE `entry`='-48';
UPDATE `creature_ai_texts` SET `content_loc7`='Espera... ¡No! ¡No!' WHERE `entry`='-49';
UPDATE `creature_ai_texts` SET `content_loc7`='No es... justo...' WHERE `entry`='-50';
UPDATE `creature_ai_texts` SET `content_loc7`='¡El destino se ha vuelto en mi contra!' WHERE `entry`='-51';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Donde estoy? ¿Que...' WHERE `entry`='-52';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Que esta pasando?' WHERE `entry`='-53';
UPDATE `creature_ai_texts` SET `content_loc7`='Lo... pagaras...' WHERE `entry`='-54';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Seras castigado!' WHERE `entry`='-55';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Cinco segundos! ¡No estoy bromeando!' WHERE `entry`='-56';
UPDATE `creature_ai_texts` SET `content_loc7`='Asi que le dije: \"Si, pero eso cuesta mas.\"' WHERE `entry`='-57';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Podriamos haber tenido tanta diversion!' WHERE `entry`='-59';
UPDATE `creature_ai_texts` SET `content_loc7`='Voy a echar de menos el espectaculo.' WHERE `entry`='-61';
UPDATE `creature_ai_texts` SET `content_loc7`='Si... Creo que ahora lo recuerdo...' WHERE `entry`='-62';
UPDATE `creature_ai_texts` SET `content_loc7`='Eso es todo... vuelve conmigo.' WHERE `entry`='-63';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Realmente se ha acabado?' WHERE `entry`='-64';
UPDATE `creature_ai_texts` SET `content_loc7`='Libre... al fin.' WHERE `entry`='-65';
UPDATE `creature_ai_texts` SET `content_loc7`='Es hora de seguir adelante...' WHERE `entry`='-66';
UPDATE `creature_ai_texts` SET `content_loc7`='La muerte es demasiado misericordiosa con vuestra especie.' WHERE `entry`='-67';
UPDATE `creature_ai_texts` SET `content_loc7`='Os espera la misma suerte a todos aquellos que intenten robar al maestro.' WHERE `entry`='-68';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Otro tomara mi lugar!' WHERE `entry`='-69';
UPDATE `creature_ai_texts` SET `content_loc7`='Esto... no cambia nada. ¡La condenacion eterna te espera!' WHERE `entry`='-70';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Da la espalda mientras puedas!' WHERE `entry`='-71';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Solo tendras exito condenandote a ti mismo!' WHERE `entry`='-72';
UPDATE `creature_ai_texts` SET `content_loc7`='Es poco aconsejable irritarme.' WHERE `entry`='-73';
UPDATE `creature_ai_texts` SET `content_loc7`='Tu estrategia era defectuosa.' WHERE `entry`='-81';
UPDATE `creature_ai_texts` SET `content_loc7`='Si, el unico resultado logico.' WHERE `entry`='-82';
UPDATE `creature_ai_texts` SET `content_loc7`='Una contingencia... imprevista...' WHERE `entry`='-83';
UPDATE `creature_ai_texts` SET `content_loc7`='Mide dos veces, corta una.' WHERE `entry`='-84';
UPDATE `creature_ai_texts` SET `content_loc7`='Si he calculado bien, ¡estareis bien muertos!' WHERE `entry`='-85';
UPDATE `creature_ai_texts` SET `content_loc7`='Pronostico una muerte dolorosa' WHERE `entry`='-86';
UPDATE `creature_ai_texts` SET `content_loc7`='Dispersaos mientras podais.' WHERE `entry`='-87';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Rayos, soy genial!' WHERE `entry`='-88';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Matones!' WHERE `entry`='-89';
UPDATE `creature_ai_texts` SET `content_loc7`='Adelante, regaladme vuestro mejor golpe. ¡Lo resistire!' WHERE `entry`='-90';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Creeis que me podeis hacer daño? ¿¡Que os tengo miedo!?' WHERE `entry`='-91';
UPDATE `creature_ai_texts` SET `content_loc7`='¡El que avisa no es traidor!' WHERE `entry`='-92';
UPDATE `creature_ai_texts` SET `content_loc7`='¡El trabajo debe continuar!' WHERE `entry`='-93';
UPDATE `creature_ai_texts` SET `content_loc7`='¡No me obligueis a mataros!' WHERE `entry`='-94';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Lo habeis provocado vosotros!' WHERE `entry`='-95';
UPDATE `creature_ai_texts` SET `content_loc7`='Tenia que hacerse.' WHERE `entry`='-96';
UPDATE `creature_ai_texts` SET `content_loc7`='No deberias haber venido.' WHERE `entry`='-97';
UPDATE `creature_ai_texts` SET `content_loc7`='Me... lo merezco.' WHERE `entry`='-98';
UPDATE `creature_ai_texts` SET `content_loc7`='Nunca despertaras al soñador.' WHERE `entry`='-99';
UPDATE `creature_ai_texts` SET `content_loc7`='¡%s deja ir un grito agudo pidiendo ayuda!' WHERE `entry`='-100';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Por los Faucedraco!' WHERE `entry`='-101';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Larga vida a los Faucedraco! ¡Que mueran sin valor, $r!' WHERE `entry`='-102';
UPDATE `creature_ai_texts` SET `content_loc7`='Cerebros...' WHERE `entry`='-103';
UPDATE `creature_ai_texts` SET `content_loc7`='Esta tierra pertenece a los enanos Hierro Negro. ¡Preparate para ver el mas alla, $c!' WHERE `entry`='-104';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Tus huesos se romperan bajo mi bota, $r!' WHERE `entry`='-105';
UPDATE `creature_ai_texts` SET `content_loc7`='¡%s entra en frenesi!' WHERE `entry`='-106';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Proteged a los inocentes!' WHERE `entry`='-107';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Sirve a la confianza publica!' WHERE `entry`='-108';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Mantened la ley!' WHERE `entry`='-109';
UPDATE `creature_ai_texts` SET `content_loc7`='¡%s explota, inundando la zona con residuos arcanos!' WHERE `entry`='-111';
UPDATE `creature_ai_texts` SET `content_loc7`='Tu mundo es nuestro ahora.' WHERE `entry`='-112';
UPDATE `creature_ai_texts` SET `content_loc7`='No puedo soportar mas dolor. Tengo que encontrar una nueva fuente.' WHERE `entry`='-114';
UPDATE `creature_ai_texts` SET `content_loc7`='¿No has hecho ya suficiente daño? ¿Tienes que perturbar tambien mi sueño?' WHERE `entry`='-115';
UPDATE `creature_ai_texts` SET `content_loc7`='¿De que sirve toda esta violencia? Lo hecho, hecho esta. He fallado a mi pueblo.' WHERE `entry`='-116';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Abandonad toda esperanza! La Legion ha vuelto para acabar lo que se empezo hace tantos años... ¡Esta vez no habra escapatoria!' WHERE `entry`='-117';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Reesh, hokta!' WHERE `entry`='-118';
UPDATE `creature_ai_texts` SET `content_loc7`='Solo es el principio... de lo que os espera...' WHERE `entry`='-119';
UPDATE `creature_ai_texts` SET `content_loc7`='No te esfuerzes...' WHERE `entry`='-120';
UPDATE `creature_ai_texts` SET `content_loc7`='Vuestro tiempo... casi se ha... agotado.' WHERE `entry`='-121';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Nadie va a salvarte!' WHERE `entry`='-122';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Soy el rey serpiente! Puedo obrar a mi antojo.' WHERE `entry`='-123';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Insolente!' WHERE `entry`='-124';
UPDATE `creature_ai_texts` SET `content_loc7`='La conquista final de la Legion esta en marcha. De nuevo la subyugacion de este mundo esta a nuestro alcance. ¡Que mueran todos!' WHERE `entry`='-125';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Sucumbid al frio helado... de la muerte!' WHERE `entry`='-126';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Hara mas frio en vuestra tumba!' WHERE `entry`='-127';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Derrumbaos y pudrios!' WHERE `entry`='-128';
UPDATE `creature_ai_texts` SET `content_loc7`='Polvo sois, y en polvo os convertireis.' WHERE `entry`='-129';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Toda forma de vida ha de perecer!' WHERE `entry`='-130';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Victoria para la Legion!' WHERE `entry`='-131';
UPDATE `creature_ai_texts` SET `content_loc7`='Habeis ganado esta batalla, pero no... la guerra...' WHERE `entry`='-132';
UPDATE `creature_ai_texts` SET `content_loc7`='Las espirales de la muerte... os aplastaran.' WHERE `entry`='-140';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Intrusos! ¡Sonad la alarma!' WHERE `entry`='-141';
UPDATE `creature_ai_texts` SET `content_loc7`='Athrikus vino a nosotros. Nos dijo que podia salvarnos del peligro. Lanzo un hechizo sobre nosotros para que nos protegiera de cualquier daño.' WHERE `entry`='-143';
UPDATE `creature_ai_texts` SET `content_loc7`='Cuando el temblor se detuvo, sus verdaderos motivos fueron revelados. Estabamos atrapados, y poco a poco fue drenando nuestra energia.' WHERE `entry`='-144';
UPDATE `creature_ai_texts` SET `content_loc7`='Habia cientos de encarcelados por su hechizo. Ahora solo unos pocos permanecen en sus carceles. el nos habla a veces sobre ello.' WHERE `entry`='-145';
UPDATE `creature_ai_texts` SET `content_loc7`='Le preocupaba que su poder se debilitara, incluso que su ultima piedra de alma se desvaneciera y muriera.' WHERE `entry`='-146';
UPDATE `creature_ai_texts` SET `content_loc7`='Su lugarteniente, Ilkurd Magthrull, posee un tomo que podria indicarnos la ubicacion de las gemas de alma restantes.' WHERE `entry`='-147';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Fantastico! ¡Gracias!' WHERE `entry`='-148';
UPDATE `creature_ai_texts` SET `content_loc7`='¡%s se vuelve inestable y comienza a desintegrarse!' WHERE `entry`='-149';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Me ayudaras a encontrar a mi perro...?' WHERE `entry`='-150';
UPDATE `creature_ai_texts` SET `content_loc7`='Echo tanto de menos a mi perro...' WHERE `entry`='-151';
UPDATE `creature_ai_texts` SET `content_loc7`='¡%s crece en tamaño al ver a $N!' WHERE `entry`='-152';
UPDATE `creature_ai_texts` SET `content_loc7`='¡La fuerza de %s se desvanece!' WHERE `entry`='-153';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Illidan prevalecera!' WHERE `entry`='-154';
UPDATE `creature_ai_texts` SET `content_loc7`='¡%s comienza a armar la bomba de proximidad!' WHERE `entry`='-155';
UPDATE `creature_ai_texts` SET `content_loc7`='¡La sangre es nuestro poder!' WHERE `entry`='-156';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Lok Narash!' WHERE `entry`='-157';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Por Kargath! ¡Por la victoria!' WHERE `entry`='-158';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Lok\'tar Illidari!' WHERE `entry`='-159';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Este mundo es NUESTRO!' WHERE `entry`='-160';
UPDATE `creature_ai_texts` SET `content_loc7`='Mmm... me encanta la deliciosa cerveza de Costasur.' WHERE `entry`='-162';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Acabad con ellos, hermanos! ¡Por la Plaga!' WHERE `entry`='-163';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Esclavizaremos a los jabaespines!' WHERE `entry`='-164';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Nos extenderemos por esta tierra yerma!' WHERE `entry`='-165';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Pronto, la Plaga dominara el mundo!' WHERE `entry`='-166';
UPDATE `creature_ai_texts` SET `content_loc7`='¡MUERE!' WHERE `entry`='-167';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Quien se atreve a molestarme? ¡Muere, $N!' WHERE `entry`='-168';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Nadie puede enfrentarse a la Hermandad!' WHERE `entry`='-169';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Y no te levantes!' WHERE `entry`='-170';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Perritos falderos, todos vosotros!' WHERE `entry`='-171';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Ignorantes! ¡Nuestra causa es justa!' WHERE `entry`='-172';
UPDATE `creature_ai_texts` SET `content_loc7`='¡La Hermandad prevalecera!' WHERE `entry`='-173';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Nos atacan! ¡A vuestros puestos, escoria! ¡Hay que rechazar al invasor!' WHERE `entry`='-174';
UPDATE `creature_ai_texts` SET `content_loc7`='Vosotros, marineros de agua dulce, sois mas fuertes de lo que yo creia. ¡Tendre que improvisar!' WHERE `entry`='-175';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Me llenais de ira!' WHERE `entry`='-176';
UPDATE `creature_ai_texts` SET `content_loc7`='Entretenedlos mientras suelto a los canes de guerra.' WHERE `entry`='-179';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Mis mascotas tienen hambre y se van a dar un festin con vuestra carne!' WHERE `entry`='-180';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Nosotros somos la verdadera Horda!' WHERE `entry`='-181';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Que? Oh, no. No me importa lo que tengas que decirme. Estoy disfrutando con tu dolor.' WHERE `entry`='-183';
UPDATE `creature_ai_texts` SET `content_loc7`='Confiesa y seras libre.' WHERE `entry`='-185';
UPDATE `creature_ai_texts` SET `content_loc7`='¡%s llama a sus huargos!' WHERE `entry`='-187';
UPDATE `creature_ai_texts` SET `content_loc7`='Puedes llegar a tener mucho calor aqui, en las Tierras Inhospitas. Pero al menos es un calor seco.' WHERE `entry`='-192';
UPDATE `creature_ai_texts` SET `content_loc7`='Algun dia sere un chico de verdad.' WHERE `entry`='-194';
UPDATE `creature_ai_texts` SET `content_loc7`='Es peligroso estar aqui, maestro. Pero te ayudare a montar guardia.' WHERE `entry`='-196';
UPDATE `creature_ai_texts` SET `content_loc7`='Podemos hacerlo mejor, mas fuerte, mas rapido. Tenemos la tecnologia. Tenemos la magia.' WHERE `entry`='-197';
UPDATE `creature_ai_texts` SET `content_loc7`='Seras presa facil, $c.' WHERE `entry`='-200';
UPDATE `creature_ai_texts` SET `content_loc7`='Mis garras destrozaran tu enclenque cuerpo, $r.' WHERE `entry`='-201';
UPDATE `creature_ai_texts` SET `content_loc7`='Hare de tu cabeza un trofeo, $r.' WHERE `entry`='-202';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Pan fresco a la venta!' WHERE `entry`='-204';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Pan recien horneado a la venta!' WHERE `entry`='-205';
UPDATE `creature_ai_texts` SET `content_loc7`='Tengo un mensaje especial para ti, $N. ¡Dice que debes morir!' WHERE `entry`='-209';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Muere en el nombre de Edwin VanCleef!' WHERE `entry`='-211';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Aaaahhhhhh!' WHERE `entry`='-212';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Aplastar!' WHERE `entry`='-213';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Matar!' WHERE `entry`='-214';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Destruir!' WHERE `entry`='-215';
UPDATE `creature_ai_texts` SET `content_loc7`='Matarte sera facil.' WHERE `entry`='-229';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Te moriras pronto!' WHERE `entry`='-230';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Te cortare!' WHERE `entry`='-231';
UPDATE `creature_ai_texts` SET `content_loc7`='%s se centra en $N.' WHERE `entry`='-237';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Idiota! ¡La esencia del halcon nunca sera tuya!' WHERE `entry`='-238';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Te atreves a molestar a los fieles seguidores del Cuervo?' WHERE `entry`='-240';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Moriras por tu arrogancia, druida!' WHERE `entry`='-241';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Te atreves a molestar a los fieles seguidores del Cuervo?' WHERE `entry`='-242';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Moriras por tu arrogancia, druida!' WHERE `entry`='-243';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Alguien puede leer el cartel de Se busca?. Grek no sabe leer.' WHERE `entry`='-244';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Grek lo prueba!' WHERE `entry`='-245';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Este aceite no es bueno para Grek! ¿Quien crees que es Grek, un monton de trapos sucios?' WHERE `entry`='-246';
UPDATE `creature_ai_texts` SET `content_loc7`='Grek toma un trago.' WHERE `entry`='-247';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Nunca pense que podria llegar a hacer aceite de mana! No creo que haya mucha demanda de ello, menos por parte de Grek, por supuesto.' WHERE `entry`='-248';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Llevaselo!' WHERE `entry`='-249';
UPDATE `creature_ai_texts` SET `content_loc7`='Aprender a leer es un trabajo sediento. Un brindis, ¿vale?' WHERE `entry`='-250';
UPDATE `creature_ai_texts` SET `content_loc7`='%s se desmaya.' WHERE `entry`='-251';
UPDATE `creature_ai_texts` SET `content_loc7`='Ven aqui, $r. ¿No quieres correr riesgos en una mazmorra, verdad? El trabajo sucio, ¿y para que? ¿Para algunas baratijas sin valor? No, lo que necesitas es uno de mis amuletos. ¡Garantizamos que funcionan!' WHERE `entry`='-252';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Hay peligros fuera de aqui, no? ¿Sabes lo que necesitas? Proteccion. ¡Puedo ayudarte a desafiar a la muerte! Tan solo usa esta piedra-fetiche del cuello, mira, ¡y luego ya podras regresar del mundo de los espiritus! Un rapido viaje hasta tu cadaver y ya estaras de vuelta.' WHERE `entry`='-253';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Amuletos maravillosos! ¡Curiosidades increibles! ¡La innovacion en el trabajo de la joyeria no tiene ningun paralelismo con los metodos, ya existentes, de la mistica del viejo Griftah! ¡Prueba tu mismo estos encantos magicos a unos precios razonables!' WHERE `entry`='-254';
UPDATE `creature_ai_texts` SET `content_loc7`='Juraria que habian mas manzanas. ¡Grok!' WHERE `entry`='-255';
UPDATE `creature_ai_texts` SET `content_loc7`='Si nadie ayuda. ¡Grok aplasta!' WHERE `entry`='-256';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Hey! ¡Hola, $r! Tengo algo para ti. ¿Has visto a algun tikbalang? Espantosas criaturas, propensas al robo a distancia. Lo que necesitas es mi protector contra tikbalangs. ¡Garantizado para mantener alejados a todos tikbalangs!' WHERE `entry`='-258';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Grok necesita ayuda! ¿Por que nadie ayuda?' WHERE `entry`='-259';
UPDATE `creature_ai_texts` SET `content_loc7`='Mog\'dorg el Marchito decir a Grok de ir a ciudad para ayudar a los Machacasangre. Grok ir.' WHERE `entry`='-260';
UPDATE `creature_ai_texts` SET `content_loc7`='El clan Aguja del Filo no pelea de manera justa. Tienen a los gronn de su lado. Ve a las Montañas Filospada y habla con Mog\'dorg el Marchito. Mata a los gronn.' WHERE `entry`='-261';
UPDATE `creature_ai_texts` SET `content_loc7`='Te veo cansado, $c. Creo que tengo algo para ti. Estos amuletos pueden ayudarte a saltar obstaculos y nadar a traves de los rios como si hubieras nacido para ello. Te permiten extraer gran cantidad de energia de la comida, ¡haciendo que las heridas se sanen delante de tus propios ojos!' WHERE `entry`='-262';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Que hace ese pobre orco gritando? Alguien deberia ver lo que esta pasando.' WHERE `entry`='-263';
UPDATE `creature_ai_texts` SET `content_loc7`='Presiento que la guerra cada vez esta mas cerca. El vendedor de frutas ha reclutado a un ogro para ayudarle. Tendre que pedir ayuda tambien.' WHERE `entry`='-264';
UPDATE `creature_ai_texts` SET `content_loc7`='Me dan hambre. Parecen sabrosas esas frutas.' WHERE `entry`='-266';
UPDATE `creature_ai_texts` SET `content_loc7`='¡VENDEDOR DE FRUTAS! ¡Tu carro sigue en nuestro camino! Te daremos una hora mas para sacarlo de nuestra zona. ¡No juegues con nuestra paciencia!' WHERE `entry`='-267';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Grok se enfada si los mequetrefes no van a Filospada y hablan con Mog\'dorg!' WHERE `entry`='-268';
UPDATE `creature_ai_texts` SET `content_loc7`='No hay nada como un buen pichel para mojar una de mis magnificas magdalenas.' WHERE `entry`='-269';
UPDATE `creature_ai_texts` SET `content_loc7`='Si, has dado en el clavo. ¡Magdalenas a la venta! ¡Consigue tus magdalenas recien hechas aqui!' WHERE `entry`='-270';
UPDATE `creature_ai_texts` SET `content_loc7`='Si, si, soy el hombre de las magdalenas. ¿Sabes por que? ¡Porque vendo magdalenas!' WHERE `entry`='-271';
UPDATE `creature_ai_texts` SET `content_loc7`='Tengo magdalenas por aqui. ¡Ven!' WHERE `entry`='-272';
UPDATE `creature_ai_texts` SET `content_loc7`='Que asi sea.' WHERE `entry`='-273';
UPDATE `creature_ai_texts` SET `content_loc7`='Anacoreta Nindumen, tengo una peticion que hacerte.' WHERE `entry`='-274';
UPDATE `creature_ai_texts` SET `content_loc7`='Acabamos de enviar otro equipo sin experiencia a Nagrand. ¿Podrias orar por ellos?' WHERE `entry`='-275';
UPDATE `creature_ai_texts` SET `content_loc7`='Que asi sea.' WHERE `entry`='-276';
UPDATE `creature_ai_texts` SET `content_loc7`='Por supuesto, amigo mio. ¿En que puedo ayudarte?' WHERE `entry`='-277';
UPDATE `creature_ai_texts` SET `content_loc7`='Una solicitud de nobles. Seria un honor, Erothem.' WHERE `entry`='-278';
UPDATE `creature_ai_texts` SET `content_loc7`='Amigos mios, por favor, unios a mi en la humilde suplica a la Luz.' WHERE `entry`='-279';
UPDATE `creature_ai_texts` SET `content_loc7`='Luz que nos abrazas, te rogamos...' WHERE `entry`='-280';
UPDATE `creature_ai_texts` SET `content_loc7`='En nuestra lucha contra la oscuridad donde hemos enviado a nuestros hijos.' WHERE `entry`='-281';
UPDATE `creature_ai_texts` SET `content_loc7`='Por favor, bendicelos y protejelos, y concedeles el exito mas que a los que buscan hacernos daño...' WHERE `entry`='-282';
UPDATE `creature_ai_texts` SET `content_loc7`='Continua la bendicion para nuestra antigua casa, por favor.' WHERE `entry`='-283';
UPDATE `creature_ai_texts` SET `content_loc7`='Bendicenos con la tolerancia de nuestros visitantes elfos.' WHERE `entry`='-284';
UPDATE `creature_ai_texts` SET `content_loc7`='Por los Naaru, que asi sea.' WHERE `entry`='-285';
UPDATE `creature_ai_texts` SET `content_loc7`='%s inclina la cabeza.' WHERE `entry`='-286';
UPDATE `creature_ai_texts` SET `content_loc7`='Hemos perdido parte de nuestros mejores soldados...' WHERE `entry`='-287';
UPDATE `creature_ai_texts` SET `content_loc7`='Pero eso no es lo peor de todo esto. Antes de que pudieramos volver hacia atras, uno de sus grupos nos vio y nos ataco.' WHERE `entry`='-288';
UPDATE `creature_ai_texts` SET `content_loc7`='No lo se, ronco. No - lo - se...' WHERE `entry`='-289';
UPDATE `creature_ai_texts` SET `content_loc7`='Orcos viles...' WHERE `entry`='-290';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Grandes bastardos rojos! ¡Mas que cualquier otro orco que hayas visto antes! Los musculos por aqui, los colmillos por alla...' WHERE `entry`='-291';
UPDATE `creature_ai_texts` SET `content_loc7`='Y asi fue, el explorador regreso inmediatamente advirtiendonos de haber visto un par de orcos en el paso inferior. No nos habian visto todavia, asi que imagino que no estarian informados.' WHERE `entry`='-292';
UPDATE `creature_ai_texts` SET `content_loc7`='Asi que ahi estabamos - mi batallon y yo, haciendo un reconocimiento de rutina por el camino del hueso. Enviamos a un explorador mas adelante para reconocer el terreno, en caso de que nos puediera sorprender algo.' WHERE `entry`='-293';
UPDATE `creature_ai_texts` SET `content_loc7`='Tomate esto, te ayudara.' WHERE `entry`='-344';
UPDATE `creature_ai_texts` SET `content_loc7`='Te pondras bien.' WHERE `entry`='-345';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Yo machacar! ¡Tu morir!' WHERE `entry`='-360';
UPDATE `creature_ai_texts` SET `content_loc7`='¡¡Raaar!!! ¡Yo machacar $R!' WHERE `entry`='-361';
UPDATE `creature_ai_texts` SET `content_loc7`='Si el Capitan se entera, sera mi fin.' WHERE `entry`='-414';
UPDATE `creature_ai_texts` SET `content_loc7`='Alguien tuvo que ayudarles.' WHERE `entry`='-415';
UPDATE `creature_ai_texts` SET `content_loc7`='De repente, estaban en todas partes.' WHERE `entry`='-416';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Kajanishu!' WHERE `entry`='-510';
UPDATE `creature_ai_texts` SET `content_loc7`='Arrrhhh... ¡Guardias!' WHERE `entry`='-548';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Guardias!' WHERE `entry`='-549';
UPDATE `creature_ai_texts` SET `content_loc7`='¡%s pide ayuda!' WHERE `entry`='-551';
UPDATE `creature_ai_texts` SET `content_loc7`='Saludos $Gciudadano:ciudadana;.' WHERE `entry`='-552';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Shaza-Kiel!' WHERE `entry`='-575';
UPDATE `creature_ai_texts` SET `content_loc7`='¡%s estara armado en 10 segundos!' WHERE `entry`='-579';
UPDATE `creature_ai_texts` SET `content_loc7`='¡%s estara armado en 5 segundos!' WHERE `entry`='-580';
UPDATE `creature_ai_texts` SET `content_loc7`='¡%s esta armado!' WHERE `entry`='-581';
UPDATE `creature_ai_texts` SET `content_loc7`='¡¡SQUAWK!! *cough* *cough* ¡Tengo que dejar de fumar!' WHERE `entry`='-583';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Imposible!' WHERE `entry`='-597';
UPDATE `creature_ai_texts` SET `content_loc7`='¡De ningun modo!' WHERE `entry`='-617';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Dinos donde se esconde tu lider!' WHERE `entry`='-655';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Por favor! Debo alimentarme de algo pronto... Un cristal de mana... un fragmento... ¡Cualquier cosa! ¡El dolor es insoportable!' WHERE `entry`='-656';
UPDATE `creature_ai_texts` SET `content_loc7`='¡No te daremos nada hasta que hables, escoria!' WHERE `entry`='-657';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Anaia?... ¿Me engañan mis ojos? ¿Eres tu de verdad?' WHERE `entry`='-661';
UPDATE `creature_ai_texts` SET `content_loc7`='El destino ha sido muy cruel al permitirnos volver a estar juntos solo tras miles de años de separacion...' WHERE `entry`='-662';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Me odias, amor mio? Por haber tenido que destruir tu forma viviente y por liberar tu espiritu de tan triste cautiverio...' WHERE `entry`='-663';
UPDATE `creature_ai_texts` SET `content_loc7`='¡No! Anaia... ¡Anaia! ¡No me abandones! Por favor...' WHERE `entry`='-664';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Como, amor mio? ¿Como encontrare fuerzas para enfrentarme a las edades del mundo sin ti a mi lado...' WHERE `entry`='-665';
UPDATE `creature_ai_texts` SET `content_loc7`='El ha sido cruel con nosotros, amor mio, pero ten por seguro que ahora si permaneceremos unidos.' WHERE `entry`='-666';
UPDATE `creature_ai_texts` SET `content_loc7`='No permitas que esto atormente tu corazon, amor mio. Me has liberado de la esclavitud y por ello te amo mas aun.' WHERE `entry`='-667';
UPDATE `creature_ai_texts` SET `content_loc7`='Desafortunadamente, esto tambien debe interrumpirse... Los lazos que me atan a este mundo se debilitan y me arrastran...' WHERE `entry`='-668';
UPDATE `creature_ai_texts` SET `content_loc7`='Adios, Cerellean, hasta que volvamos a reunirnos...' WHERE `entry`='-669';
UPDATE `creature_ai_texts` SET `content_loc7`='La suave voz de Anaia se desvanece entre la niebla, \"No olvides que siempre te amare...\"' WHERE `entry`='-670';
UPDATE `creature_ai_texts` SET `content_loc7`='Se-Señora... ¿qui-quizas necesito mas po-polvo de cadaver...?' WHERE `entry`='-723';
UPDATE `creature_ai_texts` SET `content_loc7`='Se-Señora... ¿pu-puedo pu-pulir su... armadura?' WHERE `entry`='-724';
UPDATE `creature_ai_texts` SET `content_loc7`='Se-Señora... ¿Puedo ce-cepillar su po-poderoso corcel?' WHERE `entry`='-725';
UPDATE `creature_ai_texts` SET `content_loc7`='Si, Se-Señora...' WHERE `entry`='-726';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Imposible!' WHERE `entry`='-742';
UPDATE `creature_ai_texts` SET `content_loc7`='¡JA!' WHERE `entry`='-753';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Abandonad este lugar!' WHERE `entry`='-764';
UPDATE `creature_ai_texts` SET `content_loc7`='Que lastima que sobrevivieras al accidente para morir aqui.' WHERE `entry`='-902';
UPDATE `creature_ai_texts` SET `content_loc7`='¡No te permitiremos salir de este valle!' WHERE `entry`='-903';
UPDATE `creature_ai_texts` SET `content_loc7`='Espero que hayas hecho las paces.' WHERE `entry`='-904';
UPDATE `creature_ai_texts` SET `content_loc7`='¡No me cogeras viva, escoria!' WHERE `entry`='-905';
UPDATE `creature_ai_texts` SET `content_loc7`='Buhico Cubrebosque inoculado no le gusta lo que ha sucedido.' WHERE `entry`='-906';
UPDATE `creature_ai_texts` SET `content_loc7`='El Buhico Cubrebosque inoculado parece desorientado.' WHERE `entry`='-907';
UPDATE `creature_ai_texts` SET `content_loc7`='Buhico Cubrebosque inoculado deambula sin rumbo fijo.' WHERE `entry`='-908';
UPDATE `creature_ai_texts` SET `content_loc7`='Buhico Cubrebosque inoculado parece no importarle el efecto del cristal.' WHERE `entry`='-909';
UPDATE `creature_ai_texts` SET `content_loc7`='Buhico Cubrebosque inoculado rebosa de alegria.' WHERE `entry`='-910';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Costasur pagara con sangre!' WHERE `entry`='-928';
UPDATE `creature_ai_texts` SET `content_loc7`='¡Me he alzado!' WHERE `entry`='-929';
UPDATE `creature_ai_texts` SET `content_loc7`='¡La venganza sera mia al fin!' WHERE `entry`='-930';
UPDATE `creature_ai_texts` SET `content_loc7`='¿Fue... Fue todo un sueño? Isla Bruma Azur, Isla Bruma Sangre, Marisma de Zangar, Sombraluna... incluso Zul\'Aman... ¡Jane! ¡Jane donde estas!' WHERE `entry`='-944';
UPDATE `creature_ai_texts` SET `content_loc7`='Estoy aqui, papi. Has estado dormido todo el dia. ¡Debes estar bien cansado!' WHERE `entry`='-945';
UPDATE `creature_ai_texts` SET `content_loc7`='Ah, maravilloso. No fue mas que un sueño...' WHERE `entry`='-946';
