-- ====================== --
--   ACHIEVEMENT_REWARD   --
-- ====================== --

ALTER TABLE `locales_achievement_reward` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
INSERT IGNORE INTO `locales_achievement_reward` (`entry`) SELECT `entry` FROM `achievement_reward`;

 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Nivel 80', `text_loc7` = 'Enhorabuena por tu conviccion en alcanzar la 80ª etapa de tu aventura. No hay duda de que te has entregado a la limpieza de los males que asolan Azeroth.$B$BY aunque el camino hasta aqui no ha sido facil, la autentica batalla te espera aun.$B$B¡Sigue luchando!$B$BRhonin' WHERE `entry` = '13'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = '¡Has vivido aventuras!', `text_loc7` = '¡Mirate!$B$BY yo que pensaba que habia visto cosas en este lugar helado. A este enano le parece obvio que el fuego del explorador brilla en tus ojos.$B$BViste con orgullo este tabardo, asi tus amigos sabran donde pedir direcciones cuando llegue el momento.$B$B¡Sigue viajando!$B$BBrann Barbabronce' WHERE `entry` = '45'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = '¡Por la Alianza!', `text_loc7` = 'La guerra hace furor en nuestra tierra. Solo los heroes mas valientes osan pegar a la Horda donde mas le duele. Tu eres uno de ellos.$B$BLos golpes que has asestado a los lideres de la Horda abren las puertas a nuestro ataque final. La Horda se inclinara ante la Alianza. $B$BTus logros seran recompensados. ¡Cabalga con orgullo!$B$B Tu rey' WHERE `entry` = '614'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = '¡Por la Horda!', `text_loc7` = 'En esta epoca de gran agitacion, verdaderos heroes nacen de la miseria. Tu eres uno de esos grandes heroes.$B$BLa guerra nos recae a todos. Tus esfuerzos a nuestra causa en Azeroth y tus grandes hazañas se veran recompensados. Toma este premio de Orgrimmar y cabalga hacia la gloria.$B$B¡Por la Horda!$B$B- Jefe de Guerra Thrall' WHERE `entry` = '619'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Brutalmente entregado', `text_loc7` = 'Te he estado observando, $gchico:chica;.$B$BTienes un gran talento para luchar en las arenas. Acepta este presente y llevalo con orgullo. ¡Ahora vuelve alli y muestrales como se hace!$B$BTio Sal' WHERE `entry` = '876'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Por el Triunfador', `text_loc7` = 'No podia seguir ignorando la buena coleccion de tabardos que has conseguido reunir. No creo que sea inconveniente añadir uno mas. Simplemente es que lleba acumulando polvo en mi armario durante mucho tiempo y no le doy utilidad.' WHERE `entry` = '1021'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Nuevo hogar de Cuesqui', `text_loc7` = 'He oido lo bien que cuidas de nuestros amigos peludos. Espero que no te importe, pero debo conseguir un nuevo hogar para Cuesqui. el solo se niega a jugar limpio con los demas.$B$BPor favor, asegurate de darle de comer dos veces al dia. Y, um... le tiene mania a los gatos negro.$B$B- Breanni' WHERE `entry` = '1250'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Saludos desde Darnassus', `text_loc7` = 'Tus logros han sido profundos y de largo alcance. Azeroth, con todas las recientes turbulencias, se beneficia mucho con los que tratan de liberar la tierra de maldad.$B$BSolo los que le dedican tiempo a conocer nuestras tierras entienden los sacrificios de los caidos y el valor de nuestros heroes. Y tu eres uno de esos heroes. Es de esperar que se retracte en los cuentos tus aventuras y hazañas en los proximos años.$B$BEn nombre de la Alianza, te doy las gracias, Maestro cultural.' WHERE `entry` = '1681'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Saludos desde Cima del Trueno', `text_loc7` = 'Las noticias de tus logros han llegado muy lejos. Los vientos susurran, a traves de aullido de nuestras tierras, tus admirables hazañas. Los que estan dispuestos a desafiar el mal son nuestra unica esperanza.$B$BSolo aquellos que escuchan la voz de los vientos entienden las deudas que han pagado nuestros heroes caidos para proteger a nuestro pueblo. Espero que un heroe como tu pueda vivir mucho tiempo para contar los cuentos de tus aventuras, porque solo asi podremos recordar lo mucho que tenemos que estar agradecidos.$B$BNuestro mas sincero agradecimiento, Maestro cultural.$B$B¡Por la Horda!$B$B- Cairne Pezuña de Sangre' WHERE `entry` = '1682'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'El Maestro de las Monedas', `text_loc7` = '¡Saludos y felicitaciones por la recopilacion de la serie completa de monedas de Dalaran! Como recompensa por todo tu duro trabajo hemos incluido una nueva moneda, el Sello de titanio de Dalaran. Se trata de una moneda especial que solo se concede a los mas ardientes defensores de los coleccionistas.$B$BEspero que disfrutes de este premio especial. ¡Te lo has ganado!$B$BAtentamente,$BJepetto Jugarreta' WHERE `entry` = '2096'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'La Gloria del Heroe', `text_loc7` = 'Campeon,$B$BLos susurros sobre las grandes hazañas que has realizado desde que llegastes a Rasganorte han llegado hasta el Templo del Reposo del Dragon.$B$BTu valor no debe pasar desapercibido. Por favor, acepta este regalo en nombre de los Aspectos. Juntos liberaremos el mal en Azeroth de una vez por todas.$B$BAlexstrasza la Protectora.' WHERE `entry` = '2136'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Liderar la Caballeria', `text_loc7` = 'No podia seguir ignorando lo bueno que eres con el ganado. Con toda la actividad que hay por aqui, el negocio ha ido mejor que nunca.$B$B¿Supongo que no te importara cuidar de este Draco Albino por mi? No tengo el tiempo suficiente para dedicarme a cuidar a todos estos animales.$B$B Atentamente,$BMei Francis' WHERE `entry` = '2143'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Ha sido un largo y raro viaje', `text_loc7` = 'Con los tambores de guerra resonando lejos de aqui, es facil para los habitantes de Azeroth olvidar todas las dificultades de la vida. Tu, en cambio, has mantenido la dignidad de las razas de Azeroth con tus admirables habilidades de lucha. Vamos a celebrar la victoria a lo grande, no como en las derrotas.$B$BRecuerdalo bien, juerguista. Otros pueden ser inspirados por tu buen humor,$B$BAlexstrasza la Protectora' WHERE `entry` = '2144'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Ha sido un largo y raro viaje', `text_loc7` = 'Con los tambores de guerra resonando lejos de aqui, es facil para los habitantes de Azeroth olvidar todas las dificultades de la vida. Tu, en cambio, has mantenido la dignidad de las razas de Azeroth con tus admirables habilidades de lucha. Vamos a celebrar la victoria a lo grande, no como en las derrotas.$B$BRecuerdalo bien, juerguista. Otros pueden ser inspirados por tu buen humor,$B$BAlexstrasza la Protectora' WHERE `entry` = '2145'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Caza menor', `text_loc7` = '¡Hola!$B$BTengo entendido que has logrado dar a Cuesqui un hogar calido y cariñoso. Tengo la esperanza de que puedas considerar la adopcion de otro huerfano descarriado.$B$BEste cervatillo es muy timido, pero no tendras problemas para ganarte su amistad. ¡Con el adjunto su sal favorita!$B$B- Breanni' WHERE `entry` = '2516'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Un monton de monturas', `text_loc7` = 'Tengo entendido que ahora tus establos estan casi tan llenos como los mios. ¡Impresionante!$B$BTal vez podamos ayudarnos el uno al otro... Tengo dracohalcones de sobra y espero que puedas darle a este un nuevo hogar.$B$BNaturalmente se que ha sido entrenado como montura y no como una mascota de caza, aun asi, te sera como leal e incansable como cualquier otro caballo.$B$BLe saluda una vez mas,$BMei' WHERE `entry` = '2536'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Un monton de monturas', `text_loc7` = 'Tengo entendido que ahora tus establos estan casi tan llenos como los mios. ¡Impresionante!$B$BTal vez podamos ayudarnos el uno al otro... Tengo dracohalcones de sobra y espero que puedas darle a este un nuevo hogar.$B$BNaturalmente se que ha sido entrenado como montura y no como una mascota de caza, aun asi, te sera como leal e incansable como cualquier otro caballo.$B$BLe saluda una vez mas,$BMei' WHERE `entry` = '2537'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'La Gloria del Asaltante de Ulduar', `text_loc7` = 'Estimado $N, espero que esteis bien y que hayais tenido tiempo suficiente para recuperaros de vuestras travesuras en Ulduar.$B$BMis muchachos del equipo de prospeccion encontraron a este pobre animal muerto \'cria de Draco\'. Debe haber sido un experimento de los Enanos Ferreos de la zona.$B$B¡Por suerte, hemos podido devolver a la vida el Draco y ahora mismo se encuentra perfectamente!$B$BNinguno de nosotros sabe mucho acerca de montar cualquier cosa menos de carneros y mulas de carga y ya que os debiamos un favor por lo que habeis hecho alli... Pensamos que tal vez lo aceptarias como regalo.$B$BAtentamente,$BBrann Barbabronce.' WHERE `entry` = '2957'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'La Gloria del Asaltante de Ulduar', `text_loc7` = 'Estimado $N, espero que esteis bien y que hayais tenido tiempo suficiente para recuperaros de vuestras travesuras en Ulduar.$B$BMis muchachos del equipo de prospeccion encontraron a este pobre animal muerto \'cria de Draco\'. Debe haber sido un experimento de los Enanos Ferreos de la zona.$B$B¡Por suerte, hemos podido devolver a la vida el Draco y ahora mismo se encuentra perfectamente!$B$BNinguno de nosotros sabe mucho acerca de montar cualquier cosa menos de carneros y mulas de carga y ya que os debiamos un favor por lo que habeis hecho alli... Pensamos que tal vez lo aceptarias como regalo.$B$BAtentamente,$BBrann Barbabronce.' WHERE `entry` = '2958'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Un pavo sin engullir', `text_loc7` = '¿Puedes creer que este pavo cebado ha logrado sobrevivir todo noviembre?$B$BDado que todos sus amigos fueron servidos en las mesas Generosas junto con el Chatni de arandanos y el Relleno de pan y... ooo ... Estoy ambriento. De todos modos, ahora esta solo y me preguntaba si estarias dispuesto a cuidar de el, ya que no dispongo de espacio suficiente en la tienda.$B$BTan solo debes mantenerlo alejado del fuego de la cocina. Se le pone una mirada extraña cuando se siente alreredor de ello...' WHERE `entry` = '3478'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Un pavo sin engullir', `text_loc7` = '¿Puedes creer que este pavo cebado ha logrado sobrevivir todo noviembre?$B$BDado que todos sus amigos fueron servidos en las mesas Generosas junto con el Chatni de arandanos y el Relleno de pan y... ooo ... Estoy ambriento. De todos modos, ahora esta solo y me preguntaba si estarias dispuesto a cuidar de el, ya que no dispongo de espacio suficiente en la tienda.$B$BTan solo debes mantenerlo alejado del fuego de la cocina. Se le pone una mirada extraña cuando se siente alreredor de ello...' WHERE `entry` = '3656'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Maestro de la Isla de la Conquista', `text_loc7` = 'Honorable $N,$B$BPor tus actos en la Isla de la Conquista,$Btengo el honor de entregarte este$Btabardo. Llevalo con orgullo.$B$BAlto comandante Halford Aterravermis' WHERE `entry` = '3857'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Maestro de la Isla de la Conquista', `text_loc7` = 'Honorable $N,$B$BPor tus actos en la Isla de la Conquista,$Btengo el honor de entregarte este$Btabardo. Llevalo con orgullo.$B$BAlto comandante Halford Aterravermis' WHERE `entry` = '3957'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Un tributo a la inmortalidad', `text_loc7` = '' WHERE `entry` = '4079'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Un tributo a la inmortalidad', `text_loc7` = '' WHERE `entry` = '4156'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'La gloria del asaltante de Corona de Hielo (10 j.)', `text_loc7` = '' WHERE `entry` = '4602'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'La gloria del asaltante de Corona de Hielo (25 j.)', `text_loc7` = '' WHERE `entry` = '4603'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Buscar muchisimo mas', `text_loc7` = '$gQuerido solitario:Querida solitaria;,$B$B Queremos reconocer tu tenacidad por recorrer mazmorras con gente a la que no conoces. Con un poco de suerte, les habras enseñado a los novatos cosas nuevas.$B$BSeremos breves: hemos oido que te gustan los grupos aleatorios. Y como nunca sabes que te va a tocar, te regalamos un perrito para que te haga compañia. O algo.$B$BAbrazos,$B$BTus amigos del equipo de Desarrollo de WoW' WHERE `entry` = '4478'; 
 UPDATE `locales_achievement_reward` SET `subject_loc7` = 'Conocimiento superior', `text_loc7` = 'Felicidades por completar tus estudios de Las Escuelas de la Magia Arcana. En reconocimiento a tu dedicacion, te adjunto este volumen especial para completar la serie.$B$BEn este tomo encontras de todo, entretenimiento, diversion, pero voy a dejar que lo descubras por tu $gmismo:misma;.$B$BAtentamente,$B$BRhonin' WHERE `entry` = '1956'; 
 
