-- ================== --
--    MANGOS_STRING   --
-- ================== --


ALTER TABLE `mangos_string` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;


UPDATE mangos_string SET `content_loc7`='Debes seleccionar un personaje o criatura.' WHERE entry=1;
UPDATE mangos_string SET `content_loc7`='Debes seleccionar una criatura.' WHERE entry=2;
UPDATE mangos_string SET `content_loc7`='|cffff0000[Mensaje del Sistema]: %s|r' WHERE entry=3;
UPDATE mangos_string SET `content_loc7`='|cffff0000[Mensaje de Evento]: %s|r' WHERE entry=4;
UPDATE mangos_string SET `content_loc7`='No hay ayuda para ese comando.' WHERE entry=5;
UPDATE mangos_string SET `content_loc7`='No existe ese comando' WHERE entry=6;
UPDATE mangos_string SET `content_loc7`='No existe ese subcomando' WHERE entry=7;
UPDATE mangos_string SET `content_loc7`='El comando %s tiene subcomandos: %s' WHERE entry=8;
UPDATE mangos_string SET `content_loc7`='Comandos disponibles:' WHERE entry=9;
UPDATE mangos_string SET `content_loc7`='Sintaxis incorrecta.' WHERE entry=10;
UPDATE mangos_string SET `content_loc7`='Tu nivel de cuenta es: %i' WHERE entry=11;
UPDATE mangos_string SET `content_loc7`='Jugadores conectados: %u (max: %u) Jugadores en espera: %u (max: %u)' WHERE entry=12;
UPDATE mangos_string SET `content_loc7`='Servidor en línea: %s' WHERE entry=13;
UPDATE mangos_string SET `content_loc7`='Jugador guardado.' WHERE entry=14;
UPDATE mangos_string SET `content_loc7`='Todos los jugadores guardados.' WHERE entry=15;
UPDATE mangos_string SET `content_loc7`='Estos son los MJs activos en el servidor:' WHERE entry=16;
UPDATE mangos_string SET `content_loc7`='En este momento no hay ningun MJ conectado en el servidor.' WHERE entry=17;
UPDATE mangos_string SET `content_loc7`='No puedes hacer eso volando.' WHERE entry=18;
UPDATE mangos_string SET `content_loc7`='No puedes hacer eso en Campos de Batalla.' WHERE entry=19;
UPDATE mangos_string SET `content_loc7`='El objetivo está volando y no puede hacer eso.' WHERE entry=20;
UPDATE mangos_string SET `content_loc7`='%s está volando y el comando queda invalidado.' WHERE entry=21;
UPDATE mangos_string SET `content_loc7`='No estas montando así que no puedes desmontar.' WHERE entry=22;
UPDATE mangos_string SET `content_loc7`='No puedes hacer eso luchando.' WHERE entry=23;
UPDATE mangos_string SET `content_loc7`='Ya lo usaste recientemente.' WHERE entry=24;
UPDATE mangos_string SET `content_loc7`='¡No se cambió la contraseña (error desconocido)!' WHERE entry=25;
UPDATE mangos_string SET `content_loc7`='La contraseña ha sido cambiada' WHERE entry=26;
UPDATE mangos_string SET `content_loc7`='La contraseña anterior es incorrecta.' WHERE entry=27;
UPDATE mangos_string SET `content_loc7`='Tu cuenta ahora está bloqueada.' WHERE entry=28;
UPDATE mangos_string SET `content_loc7`='Tu cuenta ahora está desbloqueada.' WHERE entry=29;
UPDATE mangos_string SET `content_loc7`=', rango' WHERE entry=30;
UPDATE mangos_string SET `content_loc7`='[conocido]' WHERE entry=31;
UPDATE mangos_string SET `content_loc7`='[aprender]' WHERE entry=32;
UPDATE mangos_string SET `content_loc7`='[pasivo]' WHERE entry=33;
UPDATE mangos_string SET `content_loc7`='[talento]' WHERE entry=34;
UPDATE mangos_string SET `content_loc7`='[activo]' WHERE entry=35;
UPDATE mangos_string SET `content_loc7`='[completo]' WHERE entry=36;
UPDATE mangos_string SET `content_loc7`='(desconectado)' WHERE entry=37;
UPDATE mangos_string SET `content_loc7`='Activado' WHERE entry=38;
UPDATE mangos_string SET `content_loc7`='Desactivado' WHERE entry=39;
UPDATE mangos_string SET `content_loc7`='Tu eres: %s' WHERE entry=40;
UPDATE mangos_string SET `content_loc7`='visible' WHERE entry=41;
UPDATE mangos_string SET `content_loc7`='invisible' WHERE entry=42;
UPDATE mangos_string SET `content_loc7`='Hecho' WHERE entry=43;
UPDATE mangos_string SET `content_loc7`='Tu' WHERE entry=44;
UPDATE mangos_string SET `content_loc7`='<desconocido>' WHERE entry=45;
UPDATE mangos_string SET `content_loc7`='<error>' WHERE entry=46;
UPDATE mangos_string SET `content_loc7`='<personaje inexistente>' WHERE entry=47;
UPDATE mangos_string SET `content_loc7`='DESCONOCIDO' WHERE entry=48;
UPDATE mangos_string SET `content_loc7`='Debes ser como minimo nivel %u para entrar.' WHERE entry=49;
UPDATE mangos_string SET `content_loc7`='Debes ser como minimo nivel %u y tener este objeto %s para entrar.' WHERE entry=50;
UPDATE mangos_string SET `content_loc7`='¡Hola! ¿Preparado para el entrenamiento?' WHERE entry=51;
UPDATE mangos_string SET `content_loc7`='Contador de objeto no válido (%u) para el objeto %u' WHERE entry=52;
UPDATE mangos_string SET `content_loc7`='El correo no puede tener más de %u objetos adjuntos' WHERE entry=53;
UPDATE mangos_string SET `content_loc7`='Las nuevas contraseñas no coinciden' WHERE entry=54;
UPDATE mangos_string SET `content_loc7`='¡La contraseña no puede ser más larga de 16 caracteres (el límite del cliente), la contraseña no se ha cambiado!' WHERE entry=55;
UPDATE mangos_string SET `content_loc7`='Mensaje del día: %s' WHERE entry=56;
UPDATE mangos_string SET `content_loc7`='Usando BD para el mundo: %s' WHERE entry=57;
UPDATE mangos_string SET `content_loc7`='Usando libreria de scripts: %s' WHERE entry=58;
UPDATE mangos_string SET `content_loc7`='Usando EventAI de criaturas: %s' WHERE entry=59;
UPDATE mangos_string SET `content_loc7`='Usuario:' WHERE entry=61;
UPDATE mangos_string SET `content_loc7`='Contraseña:' WHERE entry=62;
UPDATE mangos_string SET `content_loc7`='Susurros Habilitados' WHERE entry=63;
UPDATE mangos_string SET `content_loc7`='Susurros Deshabilitados' WHERE entry=64;
UPDATE mangos_string SET `content_loc7`='Notificación Global:' WHERE entry=100;
UPDATE mangos_string SET `content_loc7`='Mapa: %u (%s) Zona: %u (%s) Área: %u (%s) Fase: %u X: %f Y: %f Z: %f Orientación: %f grid[%u,%u]cell[%u,%u] IDMazmorra: %u ZoneX: %f ZoneY: %f GroundZ: %f FloorZ: %f Tiene datos de altura (Map: %u VMap: %u)' WHERE entry=101;
UPDATE mangos_string SET `content_loc7`='%s ya está siendo teletransportado.' WHERE entry=102;
UPDATE mangos_string SET `content_loc7`='Puedes invocar a un jugador a la mazmorra sólo si tienes el liderazgo del grupo' WHERE entry=103;
UPDATE mangos_string SET `content_loc7`='No puedes ir a la mazmorra del jugador, porque ya estas en un grupo.' WHERE entry=104;
UPDATE mangos_string SET `content_loc7`='Puedes ir a la mazmorra de ese jugador mientras no seas de su grupo sólamente si el modo MJ está activado.' WHERE entry=105;
UPDATE mangos_string SET `content_loc7`='No puedes ir hasta el jugador %s de mazmorra a mazmorra' WHERE entry=106;
UPDATE mangos_string SET `content_loc7`='No puedes invocar al jugador %s de mazmorra a mazmorra' WHERE entry=107;
UPDATE mangos_string SET `content_loc7`='Estas invocando a %s%s.' WHERE entry=108;
UPDATE mangos_string SET `content_loc7`='Has sido invocado por %s.' WHERE entry=109;
UPDATE mangos_string SET `content_loc7`='Estás teletransportando a %s%s hacia %s.' WHERE entry=110;
UPDATE mangos_string SET `content_loc7`='Estás siendo teletransportado por %s.' WHERE entry=111;
UPDATE mangos_string SET `content_loc7`='El jugador (%s) no existe.' WHERE entry=112;
UPDATE mangos_string SET `content_loc7`='Apareciendo en la posición de %s' WHERE entry=113;
UPDATE mangos_string SET `content_loc7`='%s está apareciendo en tu posición.' WHERE entry=114;
UPDATE mangos_string SET `content_loc7`='Valores incorrectos' WHERE entry=115;
UPDATE mangos_string SET `content_loc7`='No hay ningún personaje seleccionado' WHERE entry=116;
UPDATE mangos_string SET `content_loc7`='%s no está en un grupo' WHERE entry=117;
UPDATE mangos_string SET `content_loc7`='Cambiaste la VIDA de %s a %i/%i.' WHERE entry=118;
UPDATE mangos_string SET `content_loc7`='%s cambió tu VIDA a %i/%i.' WHERE entry=119;
UPDATE mangos_string SET `content_loc7`='Cambiaste el MANÁ de %s a %i/%i.' WHERE entry=120;
UPDATE mangos_string SET `content_loc7`='%s cambió tu MANÁ a %i/%i.' WHERE entry=121;
UPDATE mangos_string SET `content_loc7`='Cambiaste la ENERGÍA de %s a %i/%i.' WHERE entry=122;
UPDATE mangos_string SET `content_loc7`='%s cambió tu ENERGÍA a %i/%i.' WHERE entry=123;
UPDATE mangos_string SET `content_loc7`='Energía actual: %u' WHERE entry=124;
UPDATE mangos_string SET `content_loc7`='Cambiaste la ira de %s a %i/%i.' WHERE entry=125;
UPDATE mangos_string SET `content_loc7`='%s cambió tu ira a %i/%i.' WHERE entry=126;
UPDATE mangos_string SET `content_loc7`='Cambiaste el nivel de %s a %i.' WHERE entry=127;
UPDATE mangos_string SET `content_loc7`='GUID %i, facción es %i, flags es %i, npcflag es %i, DY flag es %i' WHERE entry=128;
UPDATE mangos_string SET `content_loc7`='Facción incorrecta: %u (No se encontró en factiontemplate.dbc)' WHERE entry=129;
UPDATE mangos_string SET `content_loc7`='Has cambiado GUID=%i Facción a %i, flags a %i, npcflag a %i, dyflag a %i.' WHERE entry=130;
UPDATE mangos_string SET `content_loc7`='Has cambiado el %s spellmod %u al valor %i para el hechizo con bit familia %u para %s.' WHERE entry=131;
UPDATE mangos_string SET `content_loc7`='%s cambió tu spellmod %u al valor %i para el hechizo con bit familia %u.' WHERE entry=132;
UPDATE mangos_string SET `content_loc7`='Ahora %s tiene acceso a todas las rutas de vuelo (hasta el cierre de sesión)' WHERE entry=133;
UPDATE mangos_string SET `content_loc7`='Ahora %s ya no tiene acceso a todas las rutas de vuelo (sólo acceso de visitante)' WHERE entry=134;
UPDATE mangos_string SET `content_loc7`='%s te ha dado acceso a todas las rutas de vuelo (hasta el cierre sesión).' WHERE entry=135;
UPDATE mangos_string SET `content_loc7`='%s te ha retirado el acceso a todas las rutas de vuelo (sólo acceso de visitante).' WHERE entry=136;
UPDATE mangos_string SET `content_loc7`='Has cambiado todas las velocidades a %2.2f veces la normal de %s.' WHERE entry=137;
UPDATE mangos_string SET `content_loc7`='%s cambió todas las velocidades a %2.2f veces la normal.' WHERE entry=138;
UPDATE mangos_string SET `content_loc7`='Has cambiado la velocidad a %2.2f veces la normal de %s.' WHERE entry=139;
UPDATE mangos_string SET `content_loc7`='%s cambió tu velocidad a %2.2f veces la normal.' WHERE entry=140;
UPDATE mangos_string SET `content_loc7`='Has cambiado la velocidad de nado a %2.2f veces la normal de %s.' WHERE entry=141;
UPDATE mangos_string SET `content_loc7`='%s cambió tu velocidad de nado a %2.2f veces la normal.' WHERE entry=142;
UPDATE mangos_string SET `content_loc7`='Has cambiado la velocidad hacia atrás a %2.2f veces la normal de %s.' WHERE entry=143;
UPDATE mangos_string SET `content_loc7`='%s cambió tu velocidad hacia atrás a %2.2f veces la normal.' WHERE entry=144;
UPDATE mangos_string SET `content_loc7`='Has cambiado la velocidad de vuelo a %2.2f veces la normal de %s.' WHERE entry=145;
UPDATE mangos_string SET `content_loc7`='%s cambió tu velocidad de vuelo a %2.2f veces la normal.' WHERE entry=146;
UPDATE mangos_string SET `content_loc7`='Has cambiado el tamaño a %2.2f de %s.' WHERE entry=147;
UPDATE mangos_string SET `content_loc7`='%s cambió tu tamaño a %2.2f.' WHERE entry=148;
UPDATE mangos_string SET `content_loc7`='No hay ninguna montura.' WHERE entry=149;
UPDATE mangos_string SET `content_loc7`='Das una montura a %s.' WHERE entry=150;
UPDATE mangos_string SET `content_loc7`='%s te entregó una montura.' WHERE entry=151;
UPDATE mangos_string SET `content_loc7`='USUARIO1: %i, AÑAD: %i, DIF: %i' WHERE entry=152;
UPDATE mangos_string SET `content_loc7`='Tomas todas las monedas de cobre de %s.' WHERE entry=153;
UPDATE mangos_string SET `content_loc7`='%s tomó todo tu cobre.' WHERE entry=154;
UPDATE mangos_string SET `content_loc7`='Tomaste %i monedas de cobre de %s.' WHERE entry=155;
UPDATE mangos_string SET `content_loc7`='%s toma %i monedas de cobre de ti.' WHERE entry=156;
UPDATE mangos_string SET `content_loc7`='Entregas %i monedas de cobre a %s.' WHERE entry=157;
UPDATE mangos_string SET `content_loc7`='%s te entrega %i monedas de cobre.' WHERE entry=158;
UPDATE mangos_string SET `content_loc7`='Escuchas el sonido %u.' WHERE entry=159;
UPDATE mangos_string SET `content_loc7`='USUARIO2: %i, AÑAD: %i, RESULT: %i' WHERE entry=160;
UPDATE mangos_string SET `content_loc7`='Eliminado bit %i en campo %i.' WHERE entry=161;
UPDATE mangos_string SET `content_loc7`='Insertado bit %i en campo %i.' WHERE entry=162;
UPDATE mangos_string SET `content_loc7`='¡La tabla de ubicación de teletransporte esta vacia!' WHERE entry=163;
UPDATE mangos_string SET `content_loc7`='¡Ubicación de Transporte no encontrada!' WHERE entry=164;
UPDATE mangos_string SET `content_loc7`='Requiere parametro de búsqueda.' WHERE entry=165;
UPDATE mangos_string SET `content_loc7`='No hay ninguna posición de transporte que coincida con tu petición.' WHERE entry=166;
UPDATE mangos_string SET `content_loc7`='Las ubicaciones encontradas son: %s' WHERE entry=168;
UPDATE mangos_string SET `content_loc7`='Correo enviado a %s' WHERE entry=169;
UPDATE mangos_string SET `content_loc7`='Intentas oir el sonido %u, pero no existe.' WHERE entry=170;
UPDATE mangos_string SET `content_loc7`='¡No puedes teletransportarte hacia ti mismo!' WHERE entry=171;
UPDATE mangos_string SET `content_loc7`='comando de consola del servidor' WHERE entry=172;
UPDATE mangos_string SET `content_loc7`='Has cambiado el poder rúnico de %s a %i/%i.' WHERE entry=173;
UPDATE mangos_string SET `content_loc7`='%s cambió tu poder rúnico a %i/%i.' WHERE entry=174;
UPDATE mangos_string SET `content_loc7`='Nivel de líquido: %f, tierra: %f, tipo: %d, estdo: %d' WHERE entry=175;
UPDATE mangos_string SET `content_loc7`='Nada seleccionado.' WHERE entry=200;
UPDATE mangos_string SET `content_loc7`='El GUID del objeto es: %s' WHERE entry=201;
UPDATE mangos_string SET `content_loc7`='El nombre es demasiado largo, sobran %i caracteres.' WHERE entry=202;
UPDATE mangos_string SET `content_loc7`='Error, el nombre sólo puede contener caracteres A-Z y a-z.' WHERE entry=203;
UPDATE mangos_string SET `content_loc7`='El subnombre es demasiado largo, sobran %i caracteres.' WHERE entry=204;
UPDATE mangos_string SET `content_loc7`='Todavia no implementado.' WHERE entry=205;
UPDATE mangos_string SET `content_loc7`='Objeto \'%i\' \'%s\' añadido a la lista con maxcount \'%i\' y incrtime \'%i\' y extendedcost \'%i\'' WHERE entry=206;
UPDATE mangos_string SET `content_loc7`='Objeto \'%i\' no encontrado en la base de datos.' WHERE entry=207;
UPDATE mangos_string SET `content_loc7`='Objeto \'%i\' \'%s\' eliminado de la lista del vendedor.' WHERE entry=208;
UPDATE mangos_string SET `content_loc7`='Objeto \'%i\' no encontrado en lista del vendedor.' WHERE entry=209;
UPDATE mangos_string SET `content_loc7`='Objeto \'%i\' (con coste extendido %i) ya se encuentra en la lista del vendedor.' WHERE entry=210;
UPDATE mangos_string SET `content_loc7`='Hechizos de %s reiniciados.' WHERE entry=211;
UPDATE mangos_string SET `content_loc7`='Los hechizos de %s serán reinciados en el próximo inicio de sesión.' WHERE entry=212;
UPDATE mangos_string SET `content_loc7`='Talentos de %s reiniciados' WHERE entry=213;
UPDATE mangos_string SET `content_loc7`='Los Talentos de %s serán reinciados en el próximo inicio de sesión.' WHERE entry=214;
UPDATE mangos_string SET `content_loc7`='Tus hechizos han sido reiniciados.' WHERE entry=215;
UPDATE mangos_string SET `content_loc7`='Tus talentos han sido reiniciados.' WHERE entry=216;
UPDATE mangos_string SET `content_loc7`='Opción desconocida \'%s\' para el comando .resetall. Introduce el nombre de la opción correctamente.' WHERE entry=217;
UPDATE mangos_string SET `content_loc7`='Los Hechizos se reiniciarán para todos los jugadores al inicio de sesión. ¡Se recomienda estrictamente que reinicie la sesión!' WHERE entry=218;
UPDATE mangos_string SET `content_loc7`='Los talentos se reiniciarán para todos los jugadores al inicio de sesión. ¡Se recomienda estrictamente que reinicie la sesión!' WHERE entry=219;
UPDATE mangos_string SET `content_loc7`='Criatura (GUID: %u) Ningún waypoint encontrado.' WHERE entry=220;
UPDATE mangos_string SET `content_loc7`='Criatura (GUID: %u) Último waypoint no encontrado.' WHERE entry=221;
UPDATE mangos_string SET `content_loc7`='Criatura (GUID: %u) Ningún waypoint encontrado - usado \'wpguid\'. Intentando encontrarlo por su posición...' WHERE entry=222;
UPDATE mangos_string SET `content_loc7`='Criatura (GUID: %u) Ningunos waypoints encontrados - Esto es un problema con la bd de MaNGOS (single float).' WHERE entry=223;
UPDATE mangos_string SET `content_loc7`='La criatura seleccionada es ignorada - se usa el GUID provisto' WHERE entry=224;
UPDATE mangos_string SET `content_loc7`='Criatura (GUID: %u) no encontrada' WHERE entry=225;
UPDATE mangos_string SET `content_loc7`='Debes seleccionar un waypoint visual.' WHERE entry=226;
UPDATE mangos_string SET `content_loc7`='No se han encontrado waypoints visuales' WHERE entry=227;
UPDATE mangos_string SET `content_loc7`='No se puede crear un waypoint visual con criaturaID: %d' WHERE entry=228;
UPDATE mangos_string SET `content_loc7`='Todos los waypoints visuales eliminados' WHERE entry=229;
UPDATE mangos_string SET `content_loc7`='No se puede crear un waypoint-criatura con ID: %d' WHERE entry=230;
UPDATE mangos_string SET `content_loc7`='No se ha definido GUID.' WHERE entry=231;
UPDATE mangos_string SET `content_loc7`='No se ha definido un número de waypoint.' WHERE entry=232;
UPDATE mangos_string SET `content_loc7`='Argumento requerido para \'%s\'.' WHERE entry=233;
UPDATE mangos_string SET `content_loc7`='Waypoint %i añadido al GUID: %d' WHERE entry=234;
UPDATE mangos_string SET `content_loc7`='Waypoint %d añadido.' WHERE entry=235;
UPDATE mangos_string SET `content_loc7`='Waypoint cambiado.' WHERE entry=236;
UPDATE mangos_string SET `content_loc7`='Waypoint %s modificado.' WHERE entry=237;
UPDATE mangos_string SET `content_loc7`='WP exportado correctamente.' WHERE entry=238;
UPDATE mangos_string SET `content_loc7`='No se han encontrado waypoints en la base de datos.' WHERE entry=239;
UPDATE mangos_string SET `content_loc7`='Archivo Importado.' WHERE entry=240;
UPDATE mangos_string SET `content_loc7`='Waypoint eliminado.' WHERE entry=241;
UPDATE mangos_string SET `content_loc7`='Atención: No se puede eliminar el WP del mundo con el ID: %d' WHERE entry=242;
UPDATE mangos_string SET `content_loc7`='Esto ocurre si el waypoint está demasiado lejos de tu personaje.' WHERE entry=243;
UPDATE mangos_string SET `content_loc7`='El WP está eliminado de la base de datos, pero no del mundo aquí.' WHERE entry=244;
UPDATE mangos_string SET `content_loc7`='Desaparecerán despues de un reinicio del servidor.' WHERE entry=245;
UPDATE mangos_string SET `content_loc7`='Waypoint %d: Info de la criatura: %s, GUID: %d' WHERE entry=246;
UPDATE mangos_string SET `content_loc7`='Tiempo de Espera: %d' WHERE entry=247;
UPDATE mangos_string SET `content_loc7`='Modelo %d: %d' WHERE entry=248;
UPDATE mangos_string SET `content_loc7`='Gesto: %d' WHERE entry=249;
UPDATE mangos_string SET `content_loc7`='Hechizo: %d' WHERE entry=250;
UPDATE mangos_string SET `content_loc7`='Texto%d (ID: %i): %s' WHERE entry=251;
UPDATE mangos_string SET `content_loc7`='AIScript: %s' WHERE entry=252;
UPDATE mangos_string SET `content_loc7`='El renombrado del Jugador %s será solicitado en el próximo inicio de sesión.' WHERE entry=253;
UPDATE mangos_string SET `content_loc7`='El renombrado del Jugador %s (GUID #%u) será solicitado en el próximo inicio de sesión.' WHERE entry=254;
UPDATE mangos_string SET `content_loc7`='Waypoint-Criatura (GUID: %u) no encontrado' WHERE entry=255;
UPDATE mangos_string SET `content_loc7`='No se pudo encontrar el PNJ...' WHERE entry=256;
UPDATE mangos_string SET `content_loc7`='Tipo de movimiento de la criatura puesto a \'%s\', waypoints eliminados (si los hay).' WHERE entry=257;
UPDATE mangos_string SET `content_loc7`='Tipo de movimiento de la criatura puesto a \'%s\', waypoints no eliminados.' WHERE entry=258;
UPDATE mangos_string SET `content_loc7`='Valor incorrecto, Usa on (Activar) u off (Desactivar)' WHERE entry=259;
UPDATE mangos_string SET `content_loc7`='Valor guardado.' WHERE entry=260;
UPDATE mangos_string SET `content_loc7`='Valor guardado, puede que tengas que reingresar o limpiar la caché de tu cliente.' WHERE entry=261;
UPDATE mangos_string SET `content_loc7`='¡ID Areatrigger %u no encontrada!' WHERE entry=262;
UPDATE mangos_string SET `content_loc7`='Objetivo de mapa o coordenadas no válidos (X: %f Y: %f MapaId: %u)' WHERE entry=263;
UPDATE mangos_string SET `content_loc7`='Coordenadas de la zona no válidas (X: %f Y: %f AreaId: %u)' WHERE entry=264;
UPDATE mangos_string SET `content_loc7`='La zona %u (%s) es parte de un mapa de la instancia %u (%s)' WHERE entry=265;
UPDATE mangos_string SET `content_loc7`='No se encontró nada.' WHERE entry=266;
UPDATE mangos_string SET `content_loc7`='¡No se encontró el Objeto!' WHERE entry=267;
UPDATE mangos_string SET `content_loc7`='¡No se encontró la Criatura!' WHERE entry=268;
UPDATE mangos_string SET `content_loc7`='Criatura eliminada' WHERE entry=270;
UPDATE mangos_string SET `content_loc7`='Criatura movida' WHERE entry=271;
UPDATE mangos_string SET `content_loc7`='¡La criatura (GUID:%u) debe estar en el mismo mapa del jugador!' WHERE entry=272;
UPDATE mangos_string SET `content_loc7`='Objeto del Juego (GUID: %u) no encontrado' WHERE entry=273;
UPDATE mangos_string SET `content_loc7`='Objeto del Juego (GUID: %u) tiene referencias en propietario no encontrado %s lista de OJ, no puede ser eliminada.' WHERE entry=274;
UPDATE mangos_string SET `content_loc7`='Objeto del Juego (GUID: %u) eliminado' WHERE entry=275;
UPDATE mangos_string SET `content_loc7`='Objeto del Juego |cffffffff|Hobjetojuego:%d|h[%s]|h|r (GUID: %u) girado' WHERE entry=276;
UPDATE mangos_string SET `content_loc7`='Objeto del Juego |cffffffff|Hobjetojuego:%d|h[%s]|h|r (GUID: %u) movido' WHERE entry=277;
UPDATE mangos_string SET `content_loc7`='Debes seleccionar un vendedor' WHERE entry=278;
UPDATE mangos_string SET `content_loc7`='Debe enviar el id para el objeto' WHERE entry=279;
UPDATE mangos_string SET `content_loc7`='El vendedor tiene demasiados objetos (máximo 128)' WHERE entry=280;
UPDATE mangos_string SET `content_loc7`='No puedes auto expulsarte, se cerrará la sesión' WHERE entry=281;
UPDATE mangos_string SET `content_loc7`='Jugador %s expulsado.' WHERE entry=282;
UPDATE mangos_string SET `content_loc7`='Aceptar Mensajes privados: %s' WHERE entry=284;
UPDATE mangos_string SET `content_loc7`='Aceptar Mansajes privados: Activado' WHERE entry=285;
UPDATE mangos_string SET `content_loc7`='Aceptar Mensajes privados: Desactivado' WHERE entry=286;
UPDATE mangos_string SET `content_loc7`='Criatura (GUID: %u) no encontrada' WHERE entry=287;
UPDATE mangos_string SET `content_loc7`='Tickets: %i - mostrar nuevos tickets: %s' WHERE entry=288;
UPDATE mangos_string SET `content_loc7`='Nuevo ticket de %s' WHERE entry=289;
UPDATE mangos_string SET `content_loc7`='Ticket de %s (Actualizado: %s): %s' WHERE entry=290;
UPDATE mangos_string SET `content_loc7`='Mostrar nuevo Ticket: ACTIVO' WHERE entry=291;
UPDATE mangos_string SET `content_loc7`='Mostrar nuevo Ticket: DESACTIVADO' WHERE entry=292;
UPDATE mangos_string SET `content_loc7`='El Ticket %i no existe.' WHERE entry=293;
UPDATE mangos_string SET `content_loc7`='Todos los Tickets eliminados.' WHERE entry=294;
UPDATE mangos_string SET `content_loc7`='Personaje %s Ticket eliminado.' WHERE entry=295;
UPDATE mangos_string SET `content_loc7`='Ticket Borrado.' WHERE entry=296;
UPDATE mangos_string SET `content_loc7`='Distancia de Reaparición cambiada a: %f' WHERE entry=297;
UPDATE mangos_string SET `content_loc7`='Tiempo de Reaparición cambiado a: %i' WHERE entry=298;
UPDATE mangos_string SET `content_loc7`='¡El honor de %s se ha establecido a %u!' WHERE entry=299;
UPDATE mangos_string SET `content_loc7`='Tu chat ha sido desactivado durante %u minutos.' WHERE entry=300;
UPDATE mangos_string SET `content_loc7`='Has desactivado el chat de %s durante %u minutos.' WHERE entry=301;
UPDATE mangos_string SET `content_loc7`='El chat del jugador ya está activado' WHERE entry=302;
UPDATE mangos_string SET `content_loc7`='Tu chat ha sido activado' WHERE entry=303;
UPDATE mangos_string SET `content_loc7`='Has activado el chat de %s.' WHERE entry=304;
UPDATE mangos_string SET `content_loc7`='¡Facción %s (%u) la reputación de %s se estableció a %5d!' WHERE entry=305;
UPDATE mangos_string SET `content_loc7`='¡Los puntos de arena de %s se establecieron a %u!' WHERE entry=306;
UPDATE mangos_string SET `content_loc7`='¡Facción no encontrada!' WHERE entry=307;
UPDATE mangos_string SET `content_loc7`='¡Facción %i desconocida!' WHERE entry=308;
UPDATE mangos_string SET `content_loc7`='Parámetro inválido %s' WHERE entry=309;
UPDATE mangos_string SET `content_loc7`='delta debe estar entre 0 y %d (inclusivo)' WHERE entry=310;
UPDATE mangos_string SET `content_loc7`='%d - |cffffffff|Hfacción:%d|h[%s]|h|r' WHERE entry=311;
UPDATE mangos_string SET `content_loc7`='[visible]' WHERE entry=312;
UPDATE mangos_string SET `content_loc7`='[en guerra]' WHERE entry=313;
UPDATE mangos_string SET `content_loc7`='[paz forzada]' WHERE entry=314;
UPDATE mangos_string SET `content_loc7`='[oculta]' WHERE entry=315;
UPDATE mangos_string SET `content_loc7`='[invisibilidad forzada]' WHERE entry=316;
UPDATE mangos_string SET `content_loc7`='[inactiva]' WHERE entry=317;
UPDATE mangos_string SET `content_loc7`='Odiado' WHERE entry=318;
UPDATE mangos_string SET `content_loc7`='Hostil' WHERE entry=319;
UPDATE mangos_string SET `content_loc7`='Enemigo' WHERE entry=320;
UPDATE mangos_string SET `content_loc7`='Neutral' WHERE entry=321;
UPDATE mangos_string SET `content_loc7`='Amistoso' WHERE entry=322;
UPDATE mangos_string SET `content_loc7`='Honorado' WHERE entry=323;
UPDATE mangos_string SET `content_loc7`='Reverenciado' WHERE entry=324;
UPDATE mangos_string SET `content_loc7`='Exaltado' WHERE entry=325;
UPDATE mangos_string SET `content_loc7`='Facción %s (%u) no puede tener reputación.' WHERE entry=326;
UPDATE mangos_string SET `content_loc7`='[sin reputación]' WHERE entry=327;
UPDATE mangos_string SET `content_loc7`='Personajes en la cuenta %s (Id: %u)' WHERE entry=328;
UPDATE mangos_string SET `content_loc7`='%s (GUID %u)' WHERE entry=329;
UPDATE mangos_string SET `content_loc7`='¡Ningún jugador encontrado!' WHERE entry=330;
UPDATE mangos_string SET `content_loc7`='Coste extendido del objeto %u inexistente' WHERE entry=331;
UPDATE mangos_string SET `content_loc7`='Modo MJ está ACTIVADO' WHERE entry=332;
UPDATE mangos_string SET `content_loc7`='Modo MJ está DESACTIVADO' WHERE entry=333;
UPDATE mangos_string SET `content_loc7`='Marca de MJ en el chat está ACTIVADA' WHERE entry=334;
UPDATE mangos_string SET `content_loc7`='Marca de MJ en el chat está DESACTIVADA' WHERE entry=335;
UPDATE mangos_string SET `content_loc7`='Has reparado todos los objetos de %s.' WHERE entry=336;
UPDATE mangos_string SET `content_loc7`='Todos tus objetos reparados por %s.' WHERE entry=337;
UPDATE mangos_string SET `content_loc7`='Activas el modo caminar sobre agua %s para %s.' WHERE entry=338;
UPDATE mangos_string SET `content_loc7`='Tienes el modo caminar sobre agua %s por %s.' WHERE entry=339;
UPDATE mangos_string SET `content_loc7`='%s esta siguiéndote ahora.' WHERE entry=340;
UPDATE mangos_string SET `content_loc7`='%s no te está siguiendo.' WHERE entry=341;
UPDATE mangos_string SET `content_loc7`='%s dejó de seguirte.' WHERE entry=342;
UPDATE mangos_string SET `content_loc7`='Criatura (Entry: %u) no puede ser domesticada.' WHERE entry=343;
UPDATE mangos_string SET `content_loc7`='Ya tienes una mascota.' WHERE entry=344;
UPDATE mangos_string SET `content_loc7`='La personalización forzada para el jugador %s será requerida al siguiente inicio de sesión.' WHERE entry=345;
UPDATE mangos_string SET `content_loc7`='La personalización forzada para el jugador %s (GUID #%u) será requerida al siguiente inicio de sesión.' WHERE entry=346;
UPDATE mangos_string SET `content_loc7`='¡Ruta de vuelo con ID %u no encontrada!' WHERE entry=347;
UPDATE mangos_string SET `content_loc7`='Objeto de Juego (Entry: %u) tiene datos incorrectos y no puede aparecer' WHERE entry=348;
UPDATE mangos_string SET `content_loc7`='%d (idx:%d) - |cffffffff|Htítulo:%d|h[%s %s]|h|r %s %s' WHERE entry=349;
UPDATE mangos_string SET `content_loc7`='%d (idx:%d) - [%s %s] %s %s' WHERE entry=350;
UPDATE mangos_string SET `content_loc7`='¡No se han encontrado títulos!' WHERE entry=351;
UPDATE mangos_string SET `content_loc7`='Id título no válido: %u' WHERE entry=352;
UPDATE mangos_string SET `content_loc7`='Título %u (%s) añadido a la lista de títulos conocidos para el jugador %s.' WHERE entry=353;
UPDATE mangos_string SET `content_loc7`='Título %u (%s) eliminado de la lista de títulos conocidos para el jugador %s.' WHERE entry=354;
UPDATE mangos_string SET `content_loc7`='Título %u (%s) activado como título actualmente seleccionado para el jugador %s.' WHERE entry=355;
UPDATE mangos_string SET `content_loc7`='Título actualmente seleccionado para el jugador %s reiniciado debido a que ya no se conoce.' WHERE entry=356;
UPDATE mangos_string SET `content_loc7`='No hay coordenadas definidas para la localización %u' WHERE entry=357;
UPDATE mangos_string SET `content_loc7`='¡No se ha encontrado la Localización!' WHERE entry=358;
UPDATE mangos_string SET `content_loc7`='%s|cffffffff|Hareatrigger_target:%u|h[apuntada %u]|h|r Mapa %u X:%f Y:%f Z:%f%s' WHERE entry=359;
UPDATE mangos_string SET `content_loc7`='%s[apuntada %u] Mapa %u X:%f Y:%f Z:%f' WHERE entry=360;
UPDATE mangos_string SET `content_loc7`='|cffffffff|Hlocalización:%u|h[apuntador %u]|h|r Mapa %u X:%f Y:%f Z:%f%s%s%s' WHERE entry=361;
UPDATE mangos_string SET `content_loc7`='[Apuntador %u] Mapa %u X:%f Y:%f Z:%f%s%s' WHERE entry=362;
UPDATE mangos_string SET `content_loc7`='(Distancia %f)' WHERE entry=363;
UPDATE mangos_string SET `content_loc7`='[Taberna]' WHERE entry=364;
UPDATE mangos_string SET `content_loc7`='[Misión]' WHERE entry=365;
UPDATE mangos_string SET `content_loc7`='Explorar misión:' WHERE entry=366;
UPDATE mangos_string SET `content_loc7`='Requiere el Nivel %u' WHERE entry=367;
UPDATE mangos_string SET `content_loc7`='Artículos necesarios:' WHERE entry=368;
UPDATE mangos_string SET `content_loc7`='Requerimientos de misión (dificualtad):' WHERE entry=369;
UPDATE mangos_string SET `content_loc7`='Claves heroicas requeridas:' WHERE entry=370;
UPDATE mangos_string SET `content_loc7`='Requerimientos de misión (dificualtad heroica):' WHERE entry=371;
UPDATE mangos_string SET `content_loc7`='¡No se encuentra el logro!' WHERE entry=372;
UPDATE mangos_string SET `content_loc7`='Respuesta: %s' WHERE entry=373;
UPDATE mangos_string SET `content_loc7`='Contador de incidencias: %i' WHERE entry=374;
UPDATE mangos_string SET `content_loc7`='El jugador %s no tiene incidencias.' WHERE entry=375;
UPDATE mangos_string SET `content_loc7`='|cffff0000[Mensaje del Sistema]:|rScripts recargados' WHERE entry=400;
UPDATE mangos_string SET `content_loc7`='Cambiaste el nivel de seguridad de la cuenta %s a %i.' WHERE entry=401;
UPDATE mangos_string SET `content_loc7`='%s cambió tu nivel de seguridad a %i.' WHERE entry=402;
UPDATE mangos_string SET `content_loc7`='No tienes suficiente nivel de seguridad para eso.' WHERE entry=403;
UPDATE mangos_string SET `content_loc7`='Movimiento de la criatura desactivado.' WHERE entry=404;
UPDATE mangos_string SET `content_loc7`='Movimiento de la criatura activado.' WHERE entry=405;
UPDATE mangos_string SET `content_loc7`='El Clima no puede cambiarse para esta zona' WHERE entry=406;
UPDATE mangos_string SET `content_loc7`='El sistema de clima está desactivado en este servidor.' WHERE entry=407;
UPDATE mangos_string SET `content_loc7`='%s ha sido baneado por %s. Motivo: %s.' WHERE entry=408;
UPDATE mangos_string SET `content_loc7`='%s fué baneado permanentemente por %s.' WHERE entry=409;
UPDATE mangos_string SET `content_loc7`='%s %s no encontrado' WHERE entry=410;
UPDATE mangos_string SET `content_loc7`='%s desbaneado.' WHERE entry=411;
UPDATE mangos_string SET `content_loc7`='Hubo un error al eliminar el baneo a %s.' WHERE entry=412;
UPDATE mangos_string SET `content_loc7`='Cuenta inexistente: %s' WHERE entry=413;
UPDATE mangos_string SET `content_loc7`='No se encontró el personaje.' WHERE entry=414;
UPDATE mangos_string SET `content_loc7`='No hay ninguna IP en la lista de baneo.' WHERE entry=415;
UPDATE mangos_string SET `content_loc7`='La cuenta %s nunca ha sido baneada' WHERE entry=416;
UPDATE mangos_string SET `content_loc7`='Historial de baneo para la cuenta %s:' WHERE entry=417;
UPDATE mangos_string SET `content_loc7`='Fecha del baneo: %s Hora: %s Aún Activo: %s Motivo: %s Puesto por: %s' WHERE entry=418;
UPDATE mangos_string SET `content_loc7`='Info.' WHERE entry=419;
UPDATE mangos_string SET `content_loc7`='Nunca.' WHERE entry=420;
UPDATE mangos_string SET `content_loc7`='Si' WHERE entry=421;
UPDATE mangos_string SET `content_loc7`='No' WHERE entry=422;
UPDATE mangos_string SET `content_loc7`='IP: %s Fecha Baneo: %s Fecha Desbaneo: %s Duración: %s Motivo: %s Puesto por: %s' WHERE entry=423;
UPDATE mangos_string SET `content_loc7`='No hay baneos de IP concidentes.' WHERE entry=424;
UPDATE mangos_string SET `content_loc7`='No hay cuenta coincidente.' WHERE entry=425;
UPDATE mangos_string SET `content_loc7`='No hay una cuenta baneada al que pertenezca un personaje coincidente.' WHERE entry=426;
UPDATE mangos_string SET `content_loc7`='Las siguientes IPs coinciden con la consulta:' WHERE entry=427;
UPDATE mangos_string SET `content_loc7`='Las siguientes cuentas coinciden con la consulta:' WHERE entry=428;
UPDATE mangos_string SET `content_loc7`='Has aprendido demasiados Hechizos/Habilidades.' WHERE entry=429;
UPDATE mangos_string SET `content_loc7`='Has aprendido todos los Hechizos de tu clase.' WHERE entry=430;
UPDATE mangos_string SET `content_loc7`='Has aprendido todos los Talentos de tu clase.' WHERE entry=431;
UPDATE mangos_string SET `content_loc7`='Has aprendido todos los idiomas.' WHERE entry=432;
UPDATE mangos_string SET `content_loc7`='Has aprendido todas las habilidades y recetas.' WHERE entry=433;
UPDATE mangos_string SET `content_loc7`='No se pudo encontrar \'%s\'' WHERE entry=434;
UPDATE mangos_string SET `content_loc7`='Id de objeto no válido: %u' WHERE entry=435;
UPDATE mangos_string SET `content_loc7`='¡Objetos no encontrados!' WHERE entry=436;
UPDATE mangos_string SET `content_loc7`='Objeto de juego inválido id: %u' WHERE entry=437;
UPDATE mangos_string SET `content_loc7`='Objetos encontrados %u: %u ( inventario %u correo %u subasta %u hermandad %u)' WHERE entry=438;
UPDATE mangos_string SET `content_loc7`='Objetos de Juego encontrados %u: %u' WHERE entry=439;
UPDATE mangos_string SET `content_loc7`='Id no válida de la criatura: %u' WHERE entry=440;
UPDATE mangos_string SET `content_loc7`='Criaturas encontradas %u: %u' WHERE entry=441;
UPDATE mangos_string SET `content_loc7`='¡No se encontró el área!' WHERE entry=442;
UPDATE mangos_string SET `content_loc7`='¡No se encontraron conjuntos de objetos!' WHERE entry=443;
UPDATE mangos_string SET `content_loc7`='¡No se encontraron habilidades!' WHERE entry=444;
UPDATE mangos_string SET `content_loc7`='¡No se encontraron hechizos!' WHERE entry=445;
UPDATE mangos_string SET `content_loc7`='¡No se encontraron misiones!' WHERE entry=446;
UPDATE mangos_string SET `content_loc7`='¡No se encontraron criaturas!' WHERE entry=447;
UPDATE mangos_string SET `content_loc7`='¡No se encontraron objetos de juego!' WHERE entry=448;
UPDATE mangos_string SET `content_loc7`='Cementerio #%u no existe.' WHERE entry=449;
UPDATE mangos_string SET `content_loc7`='Cementerio #%u ya enlazado a la zona #%u (actual).' WHERE entry=450;
UPDATE mangos_string SET `content_loc7`='Cementerio #%u enlazado a la zona #%u (actual).' WHERE entry=451;
UPDATE mangos_string SET `content_loc7`='Cementerio #%u no puede ser enlazado a la subzona o zona inexistente #%u (error interno).' WHERE entry=452;
UPDATE mangos_string SET `content_loc7`='Ninguna facción en el Cementerio con id= #%u , repara la BD' WHERE entry=454;
UPDATE mangos_string SET `content_loc7`='El equipo no es válido, por favor repare la base de datos' WHERE entry=455;
UPDATE mangos_string SET `content_loc7`='cualquiera' WHERE entry=456;
UPDATE mangos_string SET `content_loc7`='alianza' WHERE entry=457;
UPDATE mangos_string SET `content_loc7`='horda' WHERE entry=458;
UPDATE mangos_string SET `content_loc7`='Cementerio #%u (facción: %s) está más cerca de la zona enlazada #%u.' WHERE entry=459;
UPDATE mangos_string SET `content_loc7`='Zona #%u no tiene cementerios enlazados.' WHERE entry=460;
UPDATE mangos_string SET `content_loc7`='Zona #%u no tiene cementerios enlazados para la facción: %s.' WHERE entry=461;
UPDATE mangos_string SET `content_loc7`='¡Localizacón de teletransporte ya existe!' WHERE entry=462;
UPDATE mangos_string SET `content_loc7`='Localización de teletransporte añadida.' WHERE entry=463;
UPDATE mangos_string SET `content_loc7`='Localización de teletransporte NO añadida: error de base de datos.' WHERE entry=464;
UPDATE mangos_string SET `content_loc7`='Localización de teletransporte eliminada.' WHERE entry=465;
UPDATE mangos_string SET `content_loc7`='¡Rutas de vuelo no encontradas!' WHERE entry=466;
UPDATE mangos_string SET `content_loc7`='Unidad objetivo tiene %d auras:' WHERE entry=467;
UPDATE mangos_string SET `content_loc7`='id: %d ef: %d tipo: %d duración: %d duración máx: %d nombre: %s%s%s conjurador: %s' WHERE entry=468;
UPDATE mangos_string SET `content_loc7`='Unidad objetivo tiene %d auras del tipo %d:' WHERE entry=469;
UPDATE mangos_string SET `content_loc7`='id: %d ef: %d nombre: %s%s%s conjurador: %s' WHERE entry=470;
UPDATE mangos_string SET `content_loc7`='Misión %u no encontrada.' WHERE entry=471;
UPDATE mangos_string SET `content_loc7`='Misión %u se inicia con objeto. Para que funcione correctamente, por favor, añade el objeto al inventario e inicia la misión de modo normal: .additem %u' WHERE entry=472;
UPDATE mangos_string SET `content_loc7`='Mision eliminada.' WHERE entry=473;
UPDATE mangos_string SET `content_loc7`='[recompensada]' WHERE entry=474;
UPDATE mangos_string SET `content_loc7`='[completa]' WHERE entry=475;
UPDATE mangos_string SET `content_loc7`='[activa]' WHERE entry=476;
UPDATE mangos_string SET `content_loc7`='%s Modo Vuelo %s' WHERE entry=477;
UPDATE mangos_string SET `content_loc7`='Opcode %u enviado a %s' WHERE entry=478;
UPDATE mangos_string SET `content_loc7`='¡Personaje cargado correctamente!' WHERE entry=479;
UPDATE mangos_string SET `content_loc7`='¡Fallo al cargar el personaje!' WHERE entry=480;
UPDATE mangos_string SET `content_loc7`='¡Personaje volcado correctamente!' WHERE entry=481;
UPDATE mangos_string SET `content_loc7`='¡Fallo al volcar el personaje!' WHERE entry=482;
UPDATE mangos_string SET `content_loc7`='¡Hechizo %u roto y no se permite lanzar o aprender!' WHERE entry=483;
UPDATE mangos_string SET `content_loc7`='Habilidad %u (%s) para el jugador %s puesta a %u y el máximo puesto en %u (sin bonus (talentos) permanentes).' WHERE entry=484;
UPDATE mangos_string SET `content_loc7`='El jugador %s debe tener la habilidad %u(%s) antes de usar este comando.' WHERE entry=485;
UPDATE mangos_string SET `content_loc7`='Id de habilidad no válida (%u)' WHERE entry=486;
UPDATE mangos_string SET `content_loc7`='Aprendiste los hechizos/habilidades de MJ predeterminados' WHERE entry=487;
UPDATE mangos_string SET `content_loc7`='Ya conoces ese hechizo.' WHERE entry=488;
UPDATE mangos_string SET `content_loc7`='El objetivo(%s) ya conoce ese hechizo.' WHERE entry=489;
UPDATE mangos_string SET `content_loc7`='%s no conoce ese hechizo.' WHERE entry=490;
UPDATE mangos_string SET `content_loc7`='Ya olvidaste ese hechizo.' WHERE entry=491;
UPDATE mangos_string SET `content_loc7`='La reutilización para todos los hechizos fué eliminada para %s.' WHERE entry=492;
UPDATE mangos_string SET `content_loc7`='Reutilización del hechizo %u eliminada para %s.' WHERE entry=493;
UPDATE mangos_string SET `content_loc7`='Comando : Additem, itemId = %i, cantidad = %i' WHERE entry=494;
UPDATE mangos_string SET `content_loc7`='Comando : Additemset, itemsetId = %i' WHERE entry=495;
UPDATE mangos_string SET `content_loc7`='Eliminado IDobjeto = %i, cantidad = %i de %s' WHERE entry=496;
UPDATE mangos_string SET `content_loc7`='No se puede crear objeto \'%i\' (cantidad: %i)' WHERE entry=497;
UPDATE mangos_string SET `content_loc7`='¡Necesitas proporcionar un nombre de Hermandad!' WHERE entry=498;
UPDATE mangos_string SET `content_loc7`='¡Jugador no encontrado!' WHERE entry=499;
UPDATE mangos_string SET `content_loc7`='¡El jugador ya esta en una hermandad!' WHERE entry=500;
UPDATE mangos_string SET `content_loc7`='¡No se creo la hermandad! (¿ya existe?)' WHERE entry=501;
UPDATE mangos_string SET `content_loc7`='Ningún objeto del conjunto %u encontrado.' WHERE entry=502;
UPDATE mangos_string SET `content_loc7`='La distancia es: (3D) %f (2D) %f yardas.' WHERE entry=503;
UPDATE mangos_string SET `content_loc7`='Objeto \'%i\' \'%s\' Casilla Objeto %i' WHERE entry=504;
UPDATE mangos_string SET `content_loc7`='Objeto \'%i\' no existe.' WHERE entry=505;
UPDATE mangos_string SET `content_loc7`='Objeto \'%i\' \'%s\' añadido a ranura %i' WHERE entry=506;
UPDATE mangos_string SET `content_loc7`='¡Fallo de guardado del objeto!' WHERE entry=507;
UPDATE mangos_string SET `content_loc7`='%d - propietario: %s (guid: %u cuenta: %u ) %s' WHERE entry=508;
UPDATE mangos_string SET `content_loc7`='%d - remitente: %s (guid: %u cuenta: %u) receptor: %s (guid: %u cuenta: %u) %s' WHERE entry=509;
UPDATE mangos_string SET `content_loc7`='%d - propietario: %s (guid: %u cuenta: %u) %s' WHERE entry=510;
UPDATE mangos_string SET `content_loc7`='¡Tipo de enlace incorrecto!' WHERE entry=511;
UPDATE mangos_string SET `content_loc7`='%d - |cffffffff|Hobjeto:%d:0:0:0:0:0:0:0:0|h[%s]|h|r' WHERE entry=512;
UPDATE mangos_string SET `content_loc7`='%d - |cffffffff|Hmisión:%d:%d|h[%s]|h|r %s' WHERE entry=513;
UPDATE mangos_string SET `content_loc7`='%d - |cffffffff|Hentrada criatura:%d|h[%s]|h|r' WHERE entry=514;
UPDATE mangos_string SET `content_loc7`='%d%s - |cffffffff|Hcriatura:%d|h[%s X:%f Y:%f Z:%f IdMapa:%d]|h|r' WHERE entry=515;
UPDATE mangos_string SET `content_loc7`='%d - |cffffffff|Hentrada objeto de juego:%d|h[%s]|h|r' WHERE entry=516;
UPDATE mangos_string SET `content_loc7`='%d%s, Entrada %d - |cffffffff|Hobjetojuego:%d|h[%s X:%f Y:%f Z:%f IdMapa:%d]|h|r' WHERE entry=517;
UPDATE mangos_string SET `content_loc7`='%d - |cffffffff|Hconj. objetos:%d|h[%s %s]|h|r' WHERE entry=518;
UPDATE mangos_string SET `content_loc7`='|cffffffff|Htele:%s|h[%s]|h|r' WHERE entry=519;
UPDATE mangos_string SET `content_loc7`='%d - |cffffffff|Hhechizo:%d|h[%s]|h|r' WHERE entry=520;
UPDATE mangos_string SET `content_loc7`='%d - |cffffffff|Hhabilidad:%d|h[%s %s]|h|r %s %s' WHERE entry=521;
UPDATE mangos_string SET `content_loc7`='Objeto de Juego (Entry: %u) no encontrado' WHERE entry=522;
UPDATE mangos_string SET `content_loc7`='>> Objeto de Juego %s (GUID: %u) en %f %f %f. Orientación %f.' WHERE entry=523;
UPDATE mangos_string SET `content_loc7`='Objeto seleccionado: |cffffffff|Hobjetojuego:%d|h[%s]|h|r GUID: %u ID: %u X: %f Y: %f Z: %f IdMapa: %u Orientación: %f' WHERE entry=524;
UPDATE mangos_string SET `content_loc7`='>> Añadir Objeto de Juego \'%i\' (%s) (GUID: %i) añadido en \'%f %f %f\'.' WHERE entry=525;
UPDATE mangos_string SET `content_loc7`='%s (guidbajo: %u) pila de generadores de movimiento:' WHERE entry=526;
UPDATE mangos_string SET `content_loc7`='Reposo' WHERE entry=527;
UPDATE mangos_string SET `content_loc7`='Aleatorio' WHERE entry=528;
UPDATE mangos_string SET `content_loc7`='Waypoint' WHERE entry=529;
UPDATE mangos_string SET `content_loc7`='Aleatorio animal' WHERE entry=530;
UPDATE mangos_string SET `content_loc7`='Confundido' WHERE entry=531;
UPDATE mangos_string SET `content_loc7`='Apuntado al jugador %s (guidbajo %u)' WHERE entry=532;
UPDATE mangos_string SET `content_loc7`='Apuntado a la criatura %s (guidbajo %u)' WHERE entry=533;
UPDATE mangos_string SET `content_loc7`='Apuntado a <NULL>' WHERE entry=534;
UPDATE mangos_string SET `content_loc7`='Movimiento origen a (X:%f Y:%f Z:%f)' WHERE entry=535;
UPDATE mangos_string SET `content_loc7`='Movimiento origen usado para jugador?!?' WHERE entry=536;
UPDATE mangos_string SET `content_loc7`='Ruta de vuelo' WHERE entry=537;
UPDATE mangos_string SET `content_loc7`='Generador de movimiento desconocido (%u)' WHERE entry=538;
UPDATE mangos_string SET `content_loc7`='Jugador Seleccionado PNJ GUID: %u. Facción: %u. npcFlags: %u. Entrada: %u. DisplayID: %u (Nativo: %u).' WHERE entry=539;
UPDATE mangos_string SET `content_loc7`='Nivel: %u.' WHERE entry=540;
UPDATE mangos_string SET `content_loc7`='Vida (base): %u. (max): %u. (Actual): %u.' WHERE entry=541;
UPDATE mangos_string SET `content_loc7`='Flags de unidad: %u. Flags dinámicos: %u. Plantilla facción: %u.' WHERE entry=542;
UPDATE mangos_string SET `content_loc7`='Botín: %u Robar: %u Desollar: %u' WHERE entry=543;
UPDATE mangos_string SET `content_loc7`='Posición: %f %f %f.' WHERE entry=544;
UPDATE mangos_string SET `content_loc7`='¡*** Es un vendedor!' WHERE entry=545;
UPDATE mangos_string SET `content_loc7`='¡*** Es un entrenador!' WHERE entry=546;
UPDATE mangos_string SET `content_loc7`='ID Mazmorra: %u' WHERE entry=547;
UPDATE mangos_string SET `content_loc7`='Jugador%s %s (guid: %u) Cuenta: %s (id: %u) NivelMJ: %u Ultima IP: %s Latencia: %ums' WHERE entry=548;
UPDATE mangos_string SET `content_loc7`='Tiempo Jugado: %s Nivel: %u Dinero: %ug%us%uc' WHERE entry=549;
UPDATE mangos_string SET `content_loc7`='Comando .pinfo no soporta la opción \'rep\' para jugadores desconectados.' WHERE entry=550;
UPDATE mangos_string SET `content_loc7`='%s ha explorado ahora todas las zonas.' WHERE entry=551;
UPDATE mangos_string SET `content_loc7`='%s no tiene mas zonas exploradas.' WHERE entry=552;
UPDATE mangos_string SET `content_loc7`='%s ha explorado todas las zonas para ti.' WHERE entry=553;
UPDATE mangos_string SET `content_loc7`='% ha ocultado todas las zonas para ti.' WHERE entry=554;
UPDATE mangos_string SET `content_loc7`='Planeo habilitado' WHERE entry=555;
UPDATE mangos_string SET `content_loc7`='Planeo deshabilitado' WHERE entry=556;
UPDATE mangos_string SET `content_loc7`='%s te ha subido de nivel al (%i)' WHERE entry=557;
UPDATE mangos_string SET `content_loc7`='%s te ha bajado de nivel al (%i)' WHERE entry=558;
UPDATE mangos_string SET `content_loc7`='%s te ha reiniciado tu progreso del nivel.' WHERE entry=559;
UPDATE mangos_string SET `content_loc7`='Se ha establecido el area como explorada.' WHERE entry=560;
UPDATE mangos_string SET `content_loc7`='Se ha establecido el area como no explorada.' WHERE entry=561;
UPDATE mangos_string SET `content_loc7`='El índice del valor %u es demasiado grande a %s(cuenta: %u).' WHERE entry=564;
UPDATE mangos_string SET `content_loc7`='Puesto para el campo %s:%u a valor uint32: %u' WHERE entry=565;
UPDATE mangos_string SET `content_loc7`='Pones para el campo %s:%u a valor uint32: %u' WHERE entry=566;
UPDATE mangos_string SET `content_loc7`='Puesto para el campo %s:%u a valor flotante: %f' WHERE entry=567;
UPDATE mangos_string SET `content_loc7`='Pones para el campo %s:%u a valor flotante: %f' WHERE entry=568;
UPDATE mangos_string SET `content_loc7`='Obtienes %s valor uint32:[CAMPO]:%u [VALOR]:%u' WHERE entry=569;
UPDATE mangos_string SET `content_loc7`='%s tiene valor uint32:[CAMPO]:%u [VALOR]:%u' WHERE entry=570;
UPDATE mangos_string SET `content_loc7`='Obtienes %s valor flotante:[CAMPO]:%u [VALOR]:%f' WHERE entry=571;
UPDATE mangos_string SET `content_loc7`='%s tiene valor flotante:[CAMPO]:%u [VALOR]:%f' WHERE entry=572;
UPDATE mangos_string SET `content_loc7`='Modificado %s campo uint32:%u a suma con:%i = %u (%i)' WHERE entry=575;
UPDATE mangos_string SET `content_loc7`='Modificaste para %s campo uint32:%u a suma con:%i = %u (%i)' WHERE entry=576;
UPDATE mangos_string SET `content_loc7`='Ahora eres invisible.' WHERE entry=577;
UPDATE mangos_string SET `content_loc7`='Ahora eres visible.' WHERE entry=578;
UPDATE mangos_string SET `content_loc7`='El jugador o criatura seleccionados no tienen víctima.' WHERE entry=579;
UPDATE mangos_string SET `content_loc7`='Jugador %s aprendió todos los hechizos por defecto de su raza/clase y los hechizos de recompensa al completar misiones.' WHERE entry=580;
UPDATE mangos_string SET `content_loc7`='Encontrados objetos del juego cercanos (a distancia %f): %u' WHERE entry=581;
UPDATE mangos_string SET `content_loc7`='Tiempo de reaparición: Total:%s Restante:%s' WHERE entry=582;
UPDATE mangos_string SET `content_loc7`='%d - |cffffffff|Hevento juego:%d|h[%s]|h|r%s' WHERE entry=583;
UPDATE mangos_string SET `content_loc7`='¡Evento no encontrado!' WHERE entry=584;
UPDATE mangos_string SET `content_loc7`='¡El evento no existe!' WHERE entry=585;
UPDATE mangos_string SET `content_loc7`='Evento %u: %s%s Inicio: %s Fin: %s Ocurrencia: %s Longitud: %s Siguiente cambio de estado: %s' WHERE entry=586;
UPDATE mangos_string SET `content_loc7`='¡Evento %u ya activo!' WHERE entry=587;
UPDATE mangos_string SET `content_loc7`='¡Evento %u no está activo!' WHERE entry=588;
UPDATE mangos_string SET `content_loc7`='Punto de movimiento a (X:%f Y:%f Z:%f)' WHERE entry=589;
UPDATE mangos_string SET `content_loc7`='Movimiento de miedo' WHERE entry=590;
UPDATE mangos_string SET `content_loc7`='Movimiento de distracción' WHERE entry=591;
UPDATE mangos_string SET `content_loc7`='Has aprendido todos los hechizos en la profesión: %s' WHERE entry=592;
UPDATE mangos_string SET `content_loc7`='Cuentas baneadas actualmente:' WHERE entry=593;
UPDATE mangos_string SET `content_loc7`='| Cuenta | Fecha Baneo |FechaDesbaneo | Banedado Por | Motivo Baneo |' WHERE entry=594;
UPDATE mangos_string SET `content_loc7`='IPs baneadas actualmente:' WHERE entry=595;
UPDATE mangos_string SET `content_loc7`='| IP | Fecha Baneo |FechaDesbaneo | Banedado Por | Motivo Baneo |' WHERE entry=596;
UPDATE mangos_string SET `content_loc7`='Maestros de Juego actualmente:' WHERE entry=597;
UPDATE mangos_string SET `content_loc7`='| Cuenta | MJ |' WHERE entry=598;
UPDATE mangos_string SET `content_loc7`='No hay maestros de juego.' WHERE entry=599;
UPDATE mangos_string SET `content_loc7`='¡La Alianza gana!' WHERE entry=600;
UPDATE mangos_string SET `content_loc7`='¡La Horda gana!' WHERE entry=601;
UPDATE mangos_string SET `content_loc7`='La batalla por la Garganta Grito de Guerra comenzará en 1 minuto.' WHERE entry=602;
UPDATE mangos_string SET `content_loc7`='La batalla por la Garganta Grito de Guerra comenzará en 30 segundos. ¡Preparaos!' WHERE entry=603;
UPDATE mangos_string SET `content_loc7`='¡La batalla por la Garganta Grito de Guerra ha comenzado!' WHERE entry=604;
UPDATE mangos_string SET `content_loc7`='¡$n capturó la bandera de la Horda!' WHERE entry=605;
UPDATE mangos_string SET `content_loc7`='¡$n capturó la bandera de la Alianza!' WHERE entry=606;
UPDATE mangos_string SET `content_loc7`='¡$n perdió la bandera de la Horda!' WHERE entry=607;
UPDATE mangos_string SET `content_loc7`='¡$n perdió la bandera de la Alianza!' WHERE entry=608;
UPDATE mangos_string SET `content_loc7`='¡$n devolvió la bandera de la Alianza a su base!' WHERE entry=609;
UPDATE mangos_string SET `content_loc7`='¡$n devolvió la bandera de la Horda a su base!' WHERE entry=610;
UPDATE mangos_string SET `content_loc7`='¡La bandera de la Horda ha sido capturada por $n!' WHERE entry=611;
UPDATE mangos_string SET `content_loc7`='¡La bandera de la Alianza ha sido capturada por $n!' WHERE entry=612;
UPDATE mangos_string SET `content_loc7`='Las banderas ahora están en sus bases.' WHERE entry=613;
UPDATE mangos_string SET `content_loc7`='¡La bandera de la Alianza está ahora en su base!' WHERE entry=614;
UPDATE mangos_string SET `content_loc7`='¡La bandera de la Horda está ahora en su base!' WHERE entry=615;
UPDATE mangos_string SET `content_loc7`='La batalla por el Ojo de la Tormenta comenzará en 1 minuto.' WHERE entry=636;
UPDATE mangos_string SET `content_loc7`='La batalla por el Ojo de la Tormenta comenzará en 30 segundos.' WHERE entry=637;
UPDATE mangos_string SET `content_loc7`='¡La batalla por el Ojo de la Tormenta ha comenzado!' WHERE entry=638;
UPDATE mangos_string SET `content_loc7`='La Alianza' WHERE entry=650;
UPDATE mangos_string SET `content_loc7`='La Horda' WHERE entry=651;
UPDATE mangos_string SET `content_loc7`='los establos' WHERE entry=652;
UPDATE mangos_string SET `content_loc7`='la herrería' WHERE entry=653;
UPDATE mangos_string SET `content_loc7`='la granja' WHERE entry=654;
UPDATE mangos_string SET `content_loc7`='el aserradero' WHERE entry=655;
UPDATE mangos_string SET `content_loc7`='la mina' WHERE entry=656;
UPDATE mangos_string SET `content_loc7`='%s ha capturado %s' WHERE entry=657;
UPDATE mangos_string SET `content_loc7`='$n ha defendido %s' WHERE entry=658;
UPDATE mangos_string SET `content_loc7`='$n ha asaltado %s' WHERE entry=659;
UPDATE mangos_string SET `content_loc7`='¡$n reclama %s! Si nadie lo impide, ¡%s lo controlara en 1 minuto!' WHERE entry=660;
UPDATE mangos_string SET `content_loc7`='La batalla por la Cuenca de Arathi comenzará en 1 minuto.' WHERE entry=661;
UPDATE mangos_string SET `content_loc7`='La batalla por la Cuenca de Arathi comenzará en 30 segundos. ¡Preparaos!' WHERE entry=662;
UPDATE mangos_string SET `content_loc7`='¡La batalla por la Cuenca de Arathi ha comenzado!' WHERE entry=663;
UPDATE mangos_string SET `content_loc7`='¡La Alianza ha reunido $1440W recursos y está cerca de la victoria!' WHERE entry=664;
UPDATE mangos_string SET `content_loc7`='¡La Horda ha reunido $1440W recursos y está cerca de la victoria!' WHERE entry=665;
UPDATE mangos_string SET `content_loc7`='Después de la batalla en %s nuestros intentos por otorgarte la marca de Honor han fracasado. Adjuntamos la marca de Honor que no pudimos entregarte anteriormente. ¡Gracias por luchar en %s!' WHERE entry=666;
UPDATE mangos_string SET `content_loc7`='¡La Alianza ha tomado el control de la Torre de los Magos!' WHERE entry=667;
UPDATE mangos_string SET `content_loc7`='¡La Horda ha tomado el control de la Torre de los Magos!' WHERE entry=668;
UPDATE mangos_string SET `content_loc7`='¡La Alianza ha tomado el control de las Ruinas de los Draenei!' WHERE entry=669;
UPDATE mangos_string SET `content_loc7`='¡La Horda ha tomado el control de las Ruinas de los Draenei!' WHERE entry=670;
UPDATE mangos_string SET `content_loc7`='¡La Alianza ha tomado el control de la Torre de los Elfos de Sangre!' WHERE entry=671;
UPDATE mangos_string SET `content_loc7`='¡La Horda ha tomado el control de la Torre de los Elfos de Sangre!' WHERE entry=672;
UPDATE mangos_string SET `content_loc7`='¡La Alianza ha tomado el control de las Ruinas del Atracador Vil!' WHERE entry=673;
UPDATE mangos_string SET `content_loc7`='¡La Horda ha tomado el control de las Ruinas del Atracador Vil!' WHERE entry=674;
UPDATE mangos_string SET `content_loc7`='¡La Alianza ha perdido el control de la Torre de los Magos!' WHERE entry=675;
UPDATE mangos_string SET `content_loc7`='¡La Horda ha perdido el control de la Torre de los Magos!' WHERE entry=676;
UPDATE mangos_string SET `content_loc7`='¡La Alianza ha perdido el control de las Ruinas de los Draenei!' WHERE entry=677;
UPDATE mangos_string SET `content_loc7`='¡La Horda ha perdido el control de las Ruinas de los Draenei!' WHERE entry=678;
UPDATE mangos_string SET `content_loc7`='¡La Alianza ha perdido el control de la Torre de los Elfos de Sangre!' WHERE entry=679;
UPDATE mangos_string SET `content_loc7`='¡La Horda ha perdido el control de la Torre de los Elfos de Sangre!' WHERE entry=680;
UPDATE mangos_string SET `content_loc7`='¡La Alianza ha perdido el control de las Ruinas del Atracador Vil!' WHERE entry=681;
UPDATE mangos_string SET `content_loc7`='¡La Horda ha perdido el control de las Ruinas del Atracador Vil!' WHERE entry=682;
UPDATE mangos_string SET `content_loc7`='¡$s ha capturado la bandera!' WHERE entry=683;
UPDATE mangos_string SET `content_loc7`='¡La Alianza ha capturado la bandera!' WHERE entry=684;
UPDATE mangos_string SET `content_loc7`='¡La Horda ha capturado la bandera!' WHERE entry=685;
UPDATE mangos_string SET `content_loc7`='¡La bandera ha sido perdida!' WHERE entry=686;
UPDATE mangos_string SET `content_loc7`='La bandera ha sido reinicializada' WHERE entry=687;
UPDATE mangos_string SET `content_loc7`='Debes tener nivel %u para formar parte de un equipo de arena' WHERE entry=700;
UPDATE mangos_string SET `content_loc7`='¡Un minuto para que la batalla en la Arena de comienzo!' WHERE entry=701;
UPDATE mangos_string SET `content_loc7`='¡Treinta segundos para que la batalla en la Arena de comienzo!' WHERE entry=702;
UPDATE mangos_string SET `content_loc7`='¡Quince segundos para que la batalla en la Arena de comienzo!' WHERE entry=703;
UPDATE mangos_string SET `content_loc7`='¡La batalla en la Arena ha comenzado!' WHERE entry=704;
UPDATE mangos_string SET `content_loc7`='Debes esperar %s antes de hablar de nuevo.' WHERE entry=705;
UPDATE mangos_string SET `content_loc7`='Este objeto(s) tiene problemas al equiparlo/almacenarlo en el inventario.' WHERE entry=706;
UPDATE mangos_string SET `content_loc7`='%s desea no ser molestado y no puede recibir mensajes privados: %s' WHERE entry=707;
UPDATE mangos_string SET `content_loc7`='%s está alejado del teclado desde hace: %s' WHERE entry=708;
UPDATE mangos_string SET `content_loc7`='No molestar' WHERE entry=709;
UPDATE mangos_string SET `content_loc7`='Alejado del Teclado' WHERE entry=710;
UPDATE mangos_string SET `content_loc7`='Estado de cola para %s (Nvl: %u a %u) Cola en la alianza: %u (Se necesita al menos %u o más) Cola en la horda: %u (Se necesita al menos %u o más)' WHERE entry=711;
UPDATE mangos_string SET `content_loc7`='|cffff0000[Anuncio de Cola de BG]:|r %s -- [%u-%u] A: %u/%u, H: %u/%u|r' WHERE entry=712;
UPDATE mangos_string SET `content_loc7`='¡Debes ser de nivel %u para unirte a un equipo de arena!' WHERE entry=713;
UPDATE mangos_string SET `content_loc7`='No cumples los requisitos de nivel del campo de batalla' WHERE entry=715;
UPDATE mangos_string SET `content_loc7`='|cffff0000[Anuncio de Cola de BG]:|r %s -- [%u-%u] ¡Comenzado!|r' WHERE entry=717;
UPDATE mangos_string SET `content_loc7`='|cffff0000[Anuncio de Cola de Arena]:|r Todas las Arenas -- Unido : %ux%u : %u|r' WHERE entry=718;
UPDATE mangos_string SET `content_loc7`='|cffff0000[Anuncio de Cola de Arena]:|r Todas las Arenas -- Abandonó : %ux%u : %u|r' WHERE entry=719;
UPDATE mangos_string SET `content_loc7`='Tu grupo es demasiado grande para este campo de batalla. Por favor, reagrúpate para unirte.' WHERE entry=720;
UPDATE mangos_string SET `content_loc7`='Tu grupo es demasiado grande para esta arena. Por favor reagrúpate para unirte.' WHERE entry=721;
UPDATE mangos_string SET `content_loc7`='Tu grupo tiene miembros que no están en tu grupo de arena. Por favor reagrúpate para unirte.' WHERE entry=722;
UPDATE mangos_string SET `content_loc7`='Tu grupo no tiene bastantes jugadores para unirse a este combate.' WHERE entry=723;
UPDATE mangos_string SET `content_loc7`='¡El Equipo Dorado gana!' WHERE entry=724;
UPDATE mangos_string SET `content_loc7`='¡El Equipo Verde gana!' WHERE entry=725;
UPDATE mangos_string SET `content_loc7`='Tu grupo tiene un miembro desconectado. Por favor expúlsalo antes de unirte.' WHERE entry=727;
UPDATE mangos_string SET `content_loc7`='Tu grupo tiene jugadores de la facción contraria. No puedes unirte al campo de batalla como un grupo.' WHERE entry=728;
UPDATE mangos_string SET `content_loc7`='Tu grupo tiene jugadores de distintos campos de batalla. No puedes unirte como grupo.' WHERE entry=729;
UPDATE mangos_string SET `content_loc7`='Alguien de tu grupo está ya en la cola de este campo de batalla. El(la) tiene que abandonarla antes de unirte como grupo.' WHERE entry=730;
UPDATE mangos_string SET `content_loc7`='Alguien de tu grupo es Desertor. No puedes unirte como grupo.' WHERE entry=731;
UPDATE mangos_string SET `content_loc7`='Alguien de tu grupo está ya en tres colas de campo de batalla. No puedes unirte como grupo.' WHERE entry=732;
UPDATE mangos_string SET `content_loc7`='No puedes teletransportarte a un campo de batalla o mapa de arena.' WHERE entry=733;
UPDATE mangos_string SET `content_loc7`='No puedes invocar jugadores a un campo de batalla o mapa de arena.' WHERE entry=734;
UPDATE mangos_string SET `content_loc7`='Debes estar en modo MJ para teletransportarte a un jugador que esté en un campo de batalla.' WHERE entry=735;
UPDATE mangos_string SET `content_loc7`='No puedes teletransportarte a un campo de batalla desde otro. Por favor abandona el campo de batalla primero.' WHERE entry=736;
UPDATE mangos_string SET `content_loc7`='Las Arenas se han establecido a 1c1 para depuración. No te unas como grupo.' WHERE entry=737;
UPDATE mangos_string SET `content_loc7`='Las Arenas se han establecido a modo normal.' WHERE entry=738;
UPDATE mangos_string SET `content_loc7`='Los Campos de Batalla se han establecido a 1c0 para depuración.' WHERE entry=739;
UPDATE mangos_string SET `content_loc7`='Los Campos de Batalla se han establecido a modo normal.' WHERE entry=740;
UPDATE mangos_string SET `content_loc7`='Calculando puntos de Arena basándose en la clasificación de los equipos, esto puede llevar varios minutos. Por favor espera...' WHERE entry=741;
UPDATE mangos_string SET `content_loc7`='Distribuyendo los puntos de arena a los jugadores...' WHERE entry=742;
UPDATE mangos_string SET `content_loc7`='Finalizada la distribución de puntos para los jugadores conectados.' WHERE entry=743;
UPDATE mangos_string SET `content_loc7`='Modificada la cuenta jugada, puntos de arena, etc. para los equipos de arena cargados, enviando estadísticas actualizadas a los jugadores conectados...' WHERE entry=744;
UPDATE mangos_string SET `content_loc7`='Modificación realizada.' WHERE entry=745;
UPDATE mangos_string SET `content_loc7`='Finalizado el cálculo de puntos de Arena.' WHERE entry=746;
UPDATE mangos_string SET `content_loc7`='No hay suficientes jugadores. Este juego finalizará en %u mins.' WHERE entry=750;
UPDATE mangos_string SET `content_loc7`='No hay suficientes jugadores. Este juego se cerrará en %u segundos.' WHERE entry=751;
UPDATE mangos_string SET `content_loc7`='Sólamente la Alianza puede usar ese portal' WHERE entry=752;
UPDATE mangos_string SET `content_loc7`='Sólamente la Horda puede usar ese portal' WHERE entry=753;
UPDATE mangos_string SET `content_loc7`='¡%s fué destruido por la %s!' WHERE entry=759;
UPDATE mangos_string SET `content_loc7`='¡%s está siendo atacado! Si no se defiende, ¡la %s lo destruirá!' WHERE entry=760;
UPDATE mangos_string SET `content_loc7`='¡%s ha sido capturado por la %s!' WHERE entry=761;
UPDATE mangos_string SET `content_loc7`='¡%s ha sido capturado por la %s!' WHERE entry=762;
UPDATE mangos_string SET `content_loc7`='¡%s ha sido capturado por la %s!' WHERE entry=763;
UPDATE mangos_string SET `content_loc7`='¡%s está siendo atacado! Si no se defiende, ¡la %s lo capturará!' WHERE entry=764;
UPDATE mangos_string SET `content_loc7`='¡La %s ha capturado el %s! ¡Sus suministros serán usados para pedir refuerzos!' WHERE entry=765;
UPDATE mangos_string SET `content_loc7`='Mina Ferrohondo' WHERE entry=766;
UPDATE mangos_string SET `content_loc7`='Mina Dentefrío' WHERE entry=767;
UPDATE mangos_string SET `content_loc7`='Puesto de Socorro de Pico Tormenta' WHERE entry=768;
UPDATE mangos_string SET `content_loc7`='Búnker Sur de Dun Baldar' WHERE entry=769;
UPDATE mangos_string SET `content_loc7`='Búnker Norte de Dun Baldar' WHERE entry=770;
UPDATE mangos_string SET `content_loc7`='Cementerio Pico Tormenta' WHERE entry=771;
UPDATE mangos_string SET `content_loc7`='Búnker de Ala Gélida' WHERE entry=772;
UPDATE mangos_string SET `content_loc7`='Cementerio Piedrahogar' WHERE entry=773;
UPDATE mangos_string SET `content_loc7`='Búnker Piedrahogar' WHERE entry=774;
UPDATE mangos_string SET `content_loc7`='Cementerio Avalancha' WHERE entry=775;
UPDATE mangos_string SET `content_loc7`='Torre Sangre Fría' WHERE entry=776;
UPDATE mangos_string SET `content_loc7`='Cementerio Sangre Fría' WHERE entry=777;
UPDATE mangos_string SET `content_loc7`='Punta de la Torre' WHERE entry=778;
UPDATE mangos_string SET `content_loc7`='Cementerio Lobo Gélido' WHERE entry=779;
UPDATE mangos_string SET `content_loc7`='Torre Este Lobo Gélido' WHERE entry=780;
UPDATE mangos_string SET `content_loc7`='Torre Oeste Lobo Gélido' WHERE entry=781;
UPDATE mangos_string SET `content_loc7`='Puesto de Auxilio de Lobo Gélido' WHERE entry=782;
UPDATE mangos_string SET `content_loc7`='1 minuto para que comience la batalla por el Valle de Alterac.' WHERE entry=784;
UPDATE mangos_string SET `content_loc7`='30 segundos para que comience la batalla por el Valle de Alterac. ¡Preparaos!' WHERE entry=785;
UPDATE mangos_string SET `content_loc7`='¡La batalla por el Valle de Alterac ha comenzado!' WHERE entry=786;
UPDATE mangos_string SET `content_loc7`='¡El equipo de la Alianza se está quedando sin refuerzos!' WHERE entry=787;
UPDATE mangos_string SET `content_loc7`='¡El equipo de la Horda se está quedando sin refuerzos!' WHERE entry=788;
UPDATE mangos_string SET `content_loc7`='¡El General Lobo Gélido ha muerto!' WHERE entry=789;
UPDATE mangos_string SET `content_loc7`='¡El General Pico Tormenta ha muerto!' WHERE entry=790;
UPDATE mangos_string SET `content_loc7`='No tienes suficiente oro' WHERE entry=801;
UPDATE mangos_string SET `content_loc7`='No tienes suficientes espacios libres' WHERE entry=802;
UPDATE mangos_string SET `content_loc7`='Tu compañero no tiene suficientes espacios libres en la bolsa' WHERE entry=803;
UPDATE mangos_string SET `content_loc7`='No tienes permiso para realizar esa función' WHERE entry=804;
UPDATE mangos_string SET `content_loc7`='Idioma desconocido' WHERE entry=805;
UPDATE mangos_string SET `content_loc7`='No conoces ese idioma' WHERE entry=806;
UPDATE mangos_string SET `content_loc7`='Por favor proporciona el nombre del personaje' WHERE entry=807;
UPDATE mangos_string SET `content_loc7`='Jugador %s no encontrado o desconectado' WHERE entry=808;
UPDATE mangos_string SET `content_loc7`='Cuenta del personaje %s no encontrado' WHERE entry=809;
UPDATE mangos_string SET `content_loc7`='¡|Hjugador:$N|h[$N]|h ha conseguido el logro $a!' WHERE entry=810;
UPDATE mangos_string SET `content_loc7`='Maestro de Hermandad' WHERE entry=811;
UPDATE mangos_string SET `content_loc7`='Oficial' WHERE entry=812;
UPDATE mangos_string SET `content_loc7`='Veterano' WHERE entry=813;
UPDATE mangos_string SET `content_loc7`='Miembro' WHERE entry=814;
UPDATE mangos_string SET `content_loc7`='Iniciado' WHERE entry=815;
UPDATE mangos_string SET `content_loc7`='Saliendo...' WHERE entry=1000;
UPDATE mangos_string SET `content_loc7`='Cuenta eliminada: %s' WHERE entry=1001;
UPDATE mangos_string SET `content_loc7`='Cuenta %s NO eliminada (probablemente el formato de archivo sql se ha actualizado)' WHERE entry=1002;
UPDATE mangos_string SET `content_loc7`='Cuenta %s NO eliminada (error desconocido)' WHERE entry=1003;
UPDATE mangos_string SET `content_loc7`='Cuenta creada: %s' WHERE entry=1004;
UPDATE mangos_string SET `content_loc7`='El nombre de la cuenta no puede ser superior a 16 caracteres (límite del cliente), ¡no se creó la cuenta!' WHERE entry=1005;
UPDATE mangos_string SET `content_loc7`='¡Una cuenta con este nombre ya existe!' WHERE entry=1006;
UPDATE mangos_string SET `content_loc7`='Cuenta %s NO creada (probablemente el formato de archivo sql se ha actualizado)' WHERE entry=1007;
UPDATE mangos_string SET `content_loc7`='Cuenta %s no creada (error desconocido)' WHERE entry=1008;
UPDATE mangos_string SET `content_loc7`='Jugador %s (Guid: %u) Cuenta %s (Id: %u) eliminado.' WHERE entry=1009;
UPDATE mangos_string SET `content_loc7`='| ID | Cuenta | Personaje | IP | MJ | Expansión |' WHERE entry=1010;
UPDATE mangos_string SET `content_loc7`='========================================================================================' WHERE entry=1012;
UPDATE mangos_string SET `content_loc7`='| %10u |%15s| %20s | %15s |%4d| %9d |' WHERE entry=1013;
UPDATE mangos_string SET `content_loc7`='No hay jugadores conectados.' WHERE entry=1014;
UPDATE mangos_string SET `content_loc7`='Comando salir no introducido correctamente, se necesita introducirlo completamente (quit), o el comando utilizado no se encuentra en la línea de comandos de RA' WHERE entry=1015;
UPDATE mangos_string SET `content_loc7`='| GUID | Nombre | Cuenta | Fecha Borrado |' WHERE entry=1016;
UPDATE mangos_string SET `content_loc7`='| %10u | %20s | %15s (%10u) | %19s |' WHERE entry=1017;
UPDATE mangos_string SET `content_loc7`='==========================================================================================' WHERE entry=1018;
UPDATE mangos_string SET `content_loc7`='No se han encontrado personajes.' WHERE entry=1019;
UPDATE mangos_string SET `content_loc7`='Restaurando los personajes siguientes:' WHERE entry=1020;
UPDATE mangos_string SET `content_loc7`='Eliminando los personajes siguientes:' WHERE entry=1021;
UPDATE mangos_string SET `content_loc7`='¡ERROR: Solo puedes asignar un nuevo nombre si tienes seleccionado un solo personaje!' WHERE entry=1022;
UPDATE mangos_string SET `content_loc7`='Personaje \'%s\' (GUID: %u Cuenta %u) no puede ser restaurado: ¡la cuenta no existe!' WHERE entry=1023;
UPDATE mangos_string SET `content_loc7`='Personaje \'%s\' (GUID: %u Cuenta %u) no puede ser restaurado: ¡la lista de personajes de la cuenta está completa!' WHERE entry=1024;
UPDATE mangos_string SET `content_loc7`='Personaje \'%s\' (GUID: %u Cuenta %u) no puede ser restaurado: ¡el nuevo nombre ya ha sido utilizado!' WHERE entry=1025;
UPDATE mangos_string SET `content_loc7`='GUID: %u Nombre: %s Cuenta: %s (%u) Fecha: %s' WHERE entry=1026;
UPDATE mangos_string SET `content_loc7`='Estado de los filtros de Log:' WHERE entry=1027;
UPDATE mangos_string SET `content_loc7`='Todos los filtros de log puestos a: %s' WHERE entry=1028;
UPDATE mangos_string SET `content_loc7`='El Comando sólo puede ser ejecutado desde la consola Remota.' WHERE entry=1029;
UPDATE mangos_string SET `content_loc7`='La cuenta %s (Id: %u) ahora tiene la expansión %u activada.' WHERE entry=1100;
UPDATE mangos_string SET `content_loc7`='El mensaje diario cambió a: %s' WHERE entry=1101;
UPDATE mangos_string SET `content_loc7`='Mensaje enviado a %s: %s' WHERE entry=1102;
UPDATE mangos_string SET `content_loc7`='%d - %s %s' WHERE entry=1103;
UPDATE mangos_string SET `content_loc7`='%d - %s' WHERE entry=1104;
UPDATE mangos_string SET `content_loc7`='%d - %s' WHERE entry=1105;
UPDATE mangos_string SET `content_loc7`='%d - %s %s' WHERE entry=1106;
UPDATE mangos_string SET `content_loc7`='%d - %s' WHERE entry=1107;
UPDATE mangos_string SET `content_loc7`='%d - %s %s' WHERE entry=1108;
UPDATE mangos_string SET `content_loc7`='%d - %s %s %s %s' WHERE entry=1109;
UPDATE mangos_string SET `content_loc7`='%d%s - %s X:%f Y:%f Z:%f IdMapa:%d' WHERE entry=1110;
UPDATE mangos_string SET `content_loc7`='%d%s - %s X:%f Y:%f Z:%f IdMapa:%d' WHERE entry=1111;
UPDATE mangos_string SET `content_loc7`='No se ha podido abrir el archivo: %s' WHERE entry=1112;
UPDATE mangos_string SET `content_loc7`='Cuenta %s (%u) tiene el máximo de personajes permitido (límite del cliente)' WHERE entry=1113;
UPDATE mangos_string SET `content_loc7`='¡El archivo de volcado tiene datos corruptos!' WHERE entry=1114;
UPDATE mangos_string SET `content_loc7`='¡Nombre de personaje no válido!' WHERE entry=1115;
UPDATE mangos_string SET `content_loc7`='¡Guid de personaje no válido!' WHERE entry=1116;
UPDATE mangos_string SET `content_loc7`='¡El guid del personaje %u está en uso!' WHERE entry=1117;
UPDATE mangos_string SET `content_loc7`='%d - hermandad: %s (guid: %u) %s' WHERE entry=1118;
UPDATE mangos_string SET `content_loc7`='Debes utilizar masculino (male) o femenino (female) como género.' WHERE entry=1119;
UPDATE mangos_string SET `content_loc7`='Cambiaste el género de %s a %s.' WHERE entry=1120;
UPDATE mangos_string SET `content_loc7`='Tú género cambió de %s a %s.' WHERE entry=1121;
UPDATE mangos_string SET `content_loc7`='(%u/%u +perm %u +temp %u)' WHERE entry=1122;
UPDATE mangos_string SET `content_loc7`='Ninguna mascota encontrada' WHERE entry=1123;
UPDATE mangos_string SET `content_loc7`='Tipo de mascota incorrecta' WHERE entry=1124;
UPDATE mangos_string SET `content_loc7`='Tu mascota aprendió todos los talentos' WHERE entry=1125;
UPDATE mangos_string SET `content_loc7`='Los talentos de tu mascota han sido reiniciados.' WHERE entry=1126;
UPDATE mangos_string SET `content_loc7`='Talentos de la mascota %s reiniciados.' WHERE entry=1127;
UPDATE mangos_string SET `content_loc7`='%d - |cffffffff|Hrutavuelo:%u|h[%s %s]|h|r (Mapa:%u X:%f Y:%f Z:%f)' WHERE entry=1128;
UPDATE mangos_string SET `content_loc7`='%d - %s %s (Mapa:%u X:%f Y:%f Z:%f)' WHERE entry=1129;
UPDATE mangos_string SET `content_loc7`='evento comenzado %u \'%s\'' WHERE entry=1130;
UPDATE mangos_string SET `content_loc7`='evento finalizado %u \'%s\'' WHERE entry=1131;
UPDATE mangos_string SET `content_loc7`='Siguiendo al jugador %s (guidbajo %u)' WHERE entry=1132;
UPDATE mangos_string SET `content_loc7`='Siguiendo a la criatura %s (guidbajo %u)' WHERE entry=1133;
UPDATE mangos_string SET `content_loc7`='Siguiendo <NULL>' WHERE entry=1134;
UPDATE mangos_string SET `content_loc7`='Listado de talentos conocidos:' WHERE entry=1135;
UPDATE mangos_string SET `content_loc7`='(Talentos encontrados: %u puntos de talento usados: %u)' WHERE entry=1136;
UPDATE mangos_string SET `content_loc7`='%d%s - |cffffffff|Hobjetojuego:%d|h[%s X:%f Y:%f Z:%f IdMapa:%d]|h|r' WHERE entry=1137;
UPDATE mangos_string SET `content_loc7`='=================================================================================' WHERE entry=1138;
UPDATE mangos_string SET `content_loc7`='| GUID | Nombre | Raza | Clase | Nivel |' WHERE entry=1139;
UPDATE mangos_string SET `content_loc7`='| %10u | %20s | %15s | %15s | %5u |' WHERE entry=1140;
UPDATE mangos_string SET `content_loc7`='%u - |cffffffff|Hjugador:%s|h[%s]|h|r %s %s %u' WHERE entry=1141;
UPDATE mangos_string SET `content_loc7`='%u - %s (Conectado:%s IP:%s MJ:%u Expansión:%u)' WHERE entry=1142;
UPDATE mangos_string SET `content_loc7`='Aparecido por el evento %u (%s)' WHERE entry=1143;
UPDATE mangos_string SET `content_loc7`='Desaparecido por el evento %u (%s)' WHERE entry=1144;
UPDATE mangos_string SET `content_loc7`='Parte del conjunto %u' WHERE entry=1145;
UPDATE mangos_string SET `content_loc7`='Parte del conjunto %u, conjunto superior %u' WHERE entry=1146;
UPDATE mangos_string SET `content_loc7`='El conjunto(superior) %u ha aparecido por el evento %u (%s)' WHERE entry=1147;
UPDATE mangos_string SET `content_loc7`='El conjunto(superior) %u ha desaparecido por el evento %u (%s)' WHERE entry=1148;
UPDATE mangos_string SET `content_loc7`='(Conjunto %u)' WHERE entry=1149;
UPDATE mangos_string SET `content_loc7`='(Evento %i)' WHERE entry=1150;
UPDATE mangos_string SET `content_loc7`='(Conjunto %u Evento %i)' WHERE entry=1151;
UPDATE mangos_string SET `content_loc7`='Utilizable' WHERE entry=1152;
UPDATE mangos_string SET `content_loc7`='Obtienes %s valor bitstr:[CAMPO]:%u [VALOR]:%s' WHERE entry=1153;
UPDATE mangos_string SET `content_loc7`='%s tiene valor bitstr:[CAMPO]:%u [VALOR]:%s' WHERE entry=1154;
UPDATE mangos_string SET `content_loc7`='Obtienes %s valor hex:[CAMPO]:%u [VALOR]:%x' WHERE entry=1155;
UPDATE mangos_string SET `content_loc7`='%s tiene valor hex:[CAMPO]:%u [VALOR]:%x' WHERE entry=1156;
UPDATE mangos_string SET `content_loc7`='Modificado %s campo hex:%u %s %x = %x (hex)' WHERE entry=1157;
UPDATE mangos_string SET `content_loc7`='Modificaste para %s campo hex:%u %s %x = %x (hex)' WHERE entry=1158;
UPDATE mangos_string SET `content_loc7`='Modificado %s campo flotante:%u a suma con:%f = %f' WHERE entry=1159;
UPDATE mangos_string SET `content_loc7`='Modificaste para %s campo flotante:%u a suma con:%f = %f' WHERE entry=1160;
UPDATE mangos_string SET `content_loc7`='Criterio:' WHERE entry=1161;
UPDATE mangos_string SET `content_loc7`='[contador]' WHERE entry=1162;
UPDATE mangos_string SET `content_loc7`='El logro %u no existe.' WHERE entry=1163;
UPDATE mangos_string SET `content_loc7`='El criterio del logro %u no existe.' WHERE entry=1164;
UPDATE mangos_string SET `content_loc7`='El hechizo %u no tiene auras.' WHERE entry=1165;
UPDATE mangos_string SET `content_loc7`='Intentas ver la cinemática %u pero no existe.' WHERE entry=1200;
UPDATE mangos_string SET `content_loc7`='Intentas ver el video %u pero no existe.' WHERE entry=1201;
UPDATE mangos_string SET `content_loc7`='La librería de scripts no se ha encontrado o no está accesible.' WHERE entry=1166;
UPDATE mangos_string SET `content_loc7`='La librería de scripts tiene la lista de funciones incorrectas (¿obsoleta?).' WHERE entry=1167;
UPDATE mangos_string SET `content_loc7`='La librería de scripts cargada de nuevo.' WHERE entry=1168;
UPDATE mangos_string SET `content_loc7`='La librería de scripts tiene una build diferente al actual mangosd.' WHERE entry=1169;
UPDATE mangos_string SET `content_loc7`='Usando la librería de scripts: <Librería de scripts desconocida>' WHERE entry=65;
UPDATE mangos_string SET `content_loc7`='Usando la librería de scripts: <No se ha cargado ninguna librería>' WHERE entry=66;
UPDATE mangos_string SET `content_loc7`='%u - |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u Límite máximo: %u Criaturas: %u Objeto del Juego: %u Pools %u' WHERE entry=376;
UPDATE mangos_string SET `content_loc7`='No hay pools que se encuentren en el mapa \'%s\' (Id:%u)' WHERE entry=377;
UPDATE mangos_string SET `content_loc7`='Usted no puede utilizar este comando en el mapa no instanceable \'%s\' (Id:%u). Utilice .lookup pool en su lugar.' WHERE entry=378;
UPDATE mangos_string SET `content_loc7`='Usted no puede utilizar este comando sin argumentos en el mapa no instanceable \'%s\' (Id:%u).' WHERE entry=379;
UPDATE mangos_string SET `content_loc7`='%d%s - |cffffffff|HCriatura:%d|h[%s X:%f Y:%f Z:%f MapaId:%d]|h|r Probabilidad:%f %s' WHERE entry=380;
UPDATE mangos_string SET `content_loc7`='%d%s - [%s] X:%f Y:%f Z:%f MapaId:%d Probabilidad:%f %s' WHERE entry=381;
UPDATE mangos_string SET `content_loc7`='%d%s - |cffffffff|HCriatura:%d|h[%s X:%f Y:%f Z:%f MapaId:%d]|h|r %s' WHERE entry=382;
UPDATE mangos_string SET `content_loc7`='%d%s - [%s] X:%f Y:%f Z:%f MapaId:%d %s' WHERE entry=383;
UPDATE mangos_string SET `content_loc7`='%d%s - |cffffffff|HObjeto del Juego:%d|h[%s X:%f Y:%f Z:%f MapaId:%d]|h|r Probabilidad:%f %s' WHERE entry=384;
UPDATE mangos_string SET `content_loc7`='%d%s - [%s] X:%f Y:%f Z:%f MapaId:%d Probabilidad:%f %s' WHERE entry=385;
UPDATE mangos_string SET `content_loc7`='%d%s - |cffffffff|HObjeto del Juego:%d|h[%s X:%f Y:%f Z:%f MapaId:%d]|h|r %s' WHERE entry=386;
UPDATE mangos_string SET `content_loc7`='%d%s - [%s] X:%f Y:%f Z:%f MapaId:%d %s' WHERE entry=387;
UPDATE mangos_string SET `content_loc7`='Criaturas con posibilidades explícitas:' WHERE entry=388;
UPDATE mangos_string SET `content_loc7`='Criaturas con igual posibilidad:' WHERE entry=389;
UPDATE mangos_string SET `content_loc7`='Objeto del Juego con posibilidades explícitas:' WHERE entry=390;
UPDATE mangos_string SET `content_loc7`='Objeto del Juego con igual posibilidad:' WHERE entry=391;
UPDATE mangos_string SET `content_loc7`='Pool %u - Mother pool: %u |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u Límite máximot: %u' WHERE entry=392;
UPDATE mangos_string SET `content_loc7`='Pool %u - Mother pool: %u [%s] AutoSpawn: %u Límite máximo: %u' WHERE entry=393;
UPDATE mangos_string SET `content_loc7`='Pool %u - Mother pool: nada AutoSpawn: %u Límite máximo: %u' WHERE entry=394;
UPDATE mangos_string SET `content_loc7`='No se han encontrado pools' WHERE entry=395;
UPDATE mangos_string SET `content_loc7`='%u - [%s] AutoSpawn: %u Límite máximo: %u Criaturas: %u Objetos del Juego: %u Pools %u' WHERE entry=396;
UPDATE mangos_string SET `content_loc7`='Pools con posibilidades explícitas:' WHERE entry=397;
UPDATE mangos_string SET `content_loc7`='Pools con igual posibilidad:' WHERE entry=398;
UPDATE mangos_string SET `content_loc7`='%u - |cffffffff|Hpool:%u|h[%s]|h|r AutoInserción: %u LimiteMax: %u Criaturas: %u Objetos del Juego: %u Pool %u Posibilidad: %f %s' WHERE entry=399;
UPDATE mangos_string SET `content_loc7`='%u - [%s] AutoInserción: %u LimiteMax: %u Criaturas: %u Objetos de Juego: %u Pools %u Posibilidad: %f %s' WHERE entry=1500;
UPDATE mangos_string SET `content_loc7`='%u - |cffffffff|Hpool:%u|h[%s]|h|r AutoInsercion: %u LimiteMax: %u Criaturas: %u Objetos de Juego: %u Pools %u %s' WHERE entry=1501;
UPDATE mangos_string SET `content_loc7`='%u - [%s] AutoInserción: %u LimiteMax: %u Criaturas: %u Objetos de Juego: %u Pools %u %s' WHERE entry=1502;
UPDATE mangos_string SET `content_loc7`='Hechizo %u %s = %f (*1.88 = %f) DB = %f AP = %f' WHERE entry=1202;
UPDATE mangos_string SET `content_loc7`='Sanación directa' WHERE entry=1203;
UPDATE mangos_string SET `content_loc7`='Daño directo' WHERE entry=1204;
UPDATE mangos_string SET `content_loc7`='Punto sanación' WHERE entry=1205;
UPDATE mangos_string SET `content_loc7`='Punto daño' WHERE entry=1206;
